### ISSUE TITLE
chromiumChannel from package.json is ignored

### ISSUE THREAD

**Issue by jakub300** [adieuadieu/serverless-chrome#100]
Channel configured in package.json is ignored. Most likely because fields from package.json [are loaded into env variables with `npm_package_` prefix, not `npm_config_` ](https://docs.npmjs.com/misc/scripts#packagejson-vars).

https://github.com/adieuadieu/serverless-chrome/blob/0461265938aa2134be8ab6b1a01a73c40021132b/packages/lambda/scripts/postinstall.js#L17-L23

With current code it is possibile to set chrmiumChannel by adding `chromiumChannel=beta` to `.npmrc` in project directory. Same probably applies to `skip_download`.

**Comment by dholdren** [comment]
I've run into this as well

**Comment by jimsorock** [comment]
For me I had to use `serverless_chrome_skip_download = "true"` in the `.npmrc` file. README just mentions `skip_download`.
