### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by matthewp** [adieuadieu/serverless-chrome#106]
Hi all! I was wondering if there were any known performance issues with running headless chrome on Lambda? I have tested a lambda function compared to running headless on EC2 and I get something like ~200ms to load http://example.com on my EC2 instance and ~1.3s with the Lambda function (when warm).  I know that this isn't exactly scientific, so before I did more research as to why this is happening, I wanted to discuss this with the community here to see if there were any known issues. 

Could the freezing/unfreezing be the cause on Lambda?

**Comment by Bnaya** [comment]
@matthewp abit late :), but on which EC2 instance size you used and which lambda  size you used?
When using lambda with more ram you get also more CPU power
https://docs.aws.amazon.com/lambda/latest/dg/resource-model.html

**Comment by matthewp** [comment]
Sorry for not replying!  I honestly don't remember what EC2 size I was using, it was long ago. Thanks for your awesome project though.
