### ISSUE TITLE
New headless Chrome option

### ISSUE THREAD

**Issue by bluepeter** [adieuadieu/serverless-chrome#11]
See https://developers.google.com/web/updates/2017/04/headless-chrome

Hopefully this project is still going?

**Comment by adieuadieu** [comment]
Hi @bluepeter! Thanks for sharing the link. Yes; it looks like headless Chrome is almost stable! It also looks like the latest builds now support the [printToPDF](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Page/#method-printToPDF) CDP method!

**Comment by bluepeter** [comment]
Great :) Any new commits coming soon to this repo?

**Comment by adieuadieu** [comment]
@bluepeter It's taken a long time, but... here's a pre-release on a standalone lambda package. Would be great to get some feedback!

```bash
yarn add @serverless-chrome/lambda
```

Then in your Lambda handler function:

```js
const launchChrome = require('@serverless-chrome/lambda')
const CDP = require('chrome-remote-interface')

module.exports.handler = function handler (event, context, callback) {
  launchChrome({
    flags: ['--window-size=1280x1696', '--hide-scrollbars']
  })
  .then((chrome) => {
    // Chrome is now running on localhost:9222

    // do Chrome stuff here

    // for example:
    CDP.Version()
      .then((versionInfo) => {
        callback(null, {
          versionInfo,
        })
      })
      .catch((error) => {
        callback(error)
      })
  })
  .catch((error) => {
    // Chrome didn't launch correctly

    callback(error)
  })
}
```

Development is happening in the [feature/v1.0](https://github.com/adieuadieu/serverless-chrome/tree/feature/v1.0) branch

**Comment by bluepeter** [comment]
Awesome work @adieuadieu, I'm looking forward to trying this out this week! Will let you know if I find any issues.
