### ISSUE TITLE
Chromium version compatible with Puppeteer

### ISSUE THREAD

**Issue by Kikobeats** [adieuadieu/serverless-chrome#111]
Hello,

[Puppeteer releases v1.0](https://github.com/GoogleChrome/puppeteer/releases/tag/v1.0.0).

It needs, at least `Chromium 65.0.3312.0 (r526987)`

I tried using `dev` version at [v1.0.0-36](https://github.com/adieuadieu/serverless-chrome/releases/tag/v1.0.0-36) but looks it doesn't work well. Probably because isn't the exact method.

How is it possible Puppeteer needs a version that is not released yet?

**Comment by adieuadieu** [comment]
Hi @Kikobeats — I'm not sure. Better support for Puppeteer is something I'd like to achieve in serverless-chrome. The best thing I can recommend is to try to build that specific version using the scripts in this project. But, based on PR #112, I suspect that's exactly what you're doing. 😉

It doesn't seem like 65.0.3312.0 was ever a stable/beta/dev channel version as the serverless-chrome binary-building bot never built that version. It did build [65.0.3311.3](https://s3.amazonaws.com/serverless-chrome-binaries/chromium/dev/headless-chromium-65.0.3311.3-amazonlinux-2017-03.zip) and then [65.0.3315.3](https://s3.amazonaws.com/serverless-chrome-binaries/chromium/dev/headless-chromium-65.0.3315.3-amazonlinux-2017-03.zip). Those links point to the binaries.

**Comment by Kikobeats** [comment]
Nervemind, I created my own solution, working like a charm with the last puppeteer version
https://github.com/Kikobeats/aws-lambda-chrome
