### ISSUE TITLE
VPCIdNotSpecified: No default VPC for this user

### ISSUE THREAD

**Issue by Kikobeats** [adieuadieu/serverless-chrome#112]
Hey,

Following the [tutorial](https://github.com/adieuadieu/serverless-chrome/blob/master/docs/chrome.md#with-aws-ec2) to compile chromium with AWS EC2 I'm getting this error after launch the script:

```bash
❯ ./scripts/ec2-build.sh chromium beta 65.0.3312.0
Launching EC2 spot instance to build chromium version 65.0.3312.0 (beta channel)

An error occurred (VPCIdNotSpecified) when calling the RequestSpotInstances operation: No default VPC for this user
```

Any idea how I can resolve that?

**Comment by adieuadieu** [comment]
Hi @Kikobeats — easiest thing would probably be to create a default VPC [here](https://eu-west-1.console.aws.amazon.com/vpc/home?region=eu-west-1#vpcs:). Alternatively, you could add a Security Group section to the [ec2-spot-instance-specification.json](https://github.com/adieuadieu/serverless-chrome/blob/master/aws/ec2-spot-instance-specification.json#L6) file's `LaunchSpecification` section. This file is read in and used for configuration when making the ec2 request-spot-instances API call. Alternatively you might also try providing `SecurityGroupIds` and a `SubnetId` in the launch specifications.

I haven't tried this, but what you want to do is add something like:

```json
"LaunchSpecification": {

  ...

  "SecurityGroups": [
    {
      "GroupName": "my-security-group",
      "GroupId": "sg-1a2b3c4d"
    }
  ]
}
```

You'll find more information about the request-spot-instances API [here](https://docs.aws.amazon.com/cli/latest/reference/ec2/request-spot-instances.html#examples). It has some examples on launching into a nondefault VPC.
