### ISSUE TITLE
Doubt: Packages / Release

### ISSUE THREAD

**Issue by romariolopezc** [adieuadieu/serverless-chrome#113]
Hi, I currently use the chrome headless from https://github.com/adieuadieu/serverless-chrome/tree/master/packages/lambda/chrome.

My question is: Can I use https://github.com/adieuadieu/serverless-chrome/releases/tag/v1.0.0-36 to have an updated chrome headless?

PS. Thanks for this software! 👍

**Comment by adieuadieu** [comment]
Hi @romariolopezc — Yes; that's the idea. Releases are regularly updated with the latest versions of Chrome for AWS Lambda. Eventually I will remove the binaries that are committed in the repository (some are nearly 1 year old!)
