### ISSUE TITLE
Support for OpenFaaS

### ISSUE THREAD

**Issue by alexellis** [adieuadieu/serverless-chrome#115]
Hi @adieuadieu,

I would like to suggest trying this out with OpenFaaS - OpenFaaS supports "Dockerfile" as a template for functions. I suspect it would make this much simpler - you could probably even re-use the same Lambci image.

OpenFaaS is for Kubernetes and Docker Swarm and can be hosted on your own EC2 instances or wherever you want. GKE / AKS offer a more flexible billing model.

In the readme you mention possible support for Azure / GCP in the future - this could work on any cloud. Thought this might be worth having a go at? What do you think?

More at https://www.openfaas.com/

Alex

**Comment by adieuadieu** [comment]
Hi @alexellis — Yea. Makes sense. I've been watching your progress on OpenFaas for quite a while now—nice work! (derek, too.) Could be a good excuse to finally play with OpenFaas on something "real"(ish(er)). As with most things.. It's all about _time_. In the meantime, I'm open to PRs to help push it along if someone has interest.

**Comment by Bnaya** [comment]
OpenFaaS should able to use puppeteer directly, but serverless-chrome will make super compact images for sure
