### ISSUE TITLE
Headless-chromium binaries size over 100MB. Question

### ISSUE THREAD

**Issue by JorjikS** [adieuadieu/serverless-chrome#118]
After running "npm install @serverless-chrome/lambda" headless-chromium binaries size is 101.5 MB vs to 40.5MB 2 weeks ago. Checked releases page and v1.0.0-38 stable version size is still 40.5MB. Is it expected size for new version?
Update: tried to install v1.0.0-35 and the same result with binaries size. :(

**Comment by JorjikS** [comment]
issues with my machine settings.

**Comment by onoranzefunebricloud** [comment]
@JorjikS could you describe what the issue is? I am experiencing the same
