### ISSUE TITLE
Download binary in a zip and unzip locally as a function of @serverless-chrome/lambda

### ISSUE THREAD

**Issue by andyevansweather** [adieuadieu/serverless-chrome#119]
I have researched #117 a bit further and due to our network, we cannot download binaries directly, so the npm install of @serverless-chrome/lambda fails.

As a new feature, could the binary be downloaded as a tar or zip, then uninstalled on the local machine so that I can use it and the npm install succeeds?

I don't have any admin rights to run any commands as an admin and we use windows 10 machines here.

**Comment by adieuadieu** [comment]
Hi @andyevansweather — Unless I've misunderstood, this is exactly what the `@serverless-chrome/lambda` package does. After a`yarn|npm install`, the package runs a [post-install script](https://github.com/adieuadieu/serverless-chrome/blob/master/packages/lambda/scripts/postinstall.js) which downloads the chrome binary via the corresponding zip file from the projects' [Releases](https://github.com/adieuadieu/serverless-chrome/releases). It then extracts the chrome binary from the downloaded zip.

Perhaps the script isn't working properly on Windows? Are you seeing any errors when you install the `@serverless-chrome/lambda` package?

Alternatively, you could do the process manually. First download the zip file from the [Releases](https://github.com/adieuadieu/serverless-chrome/releases) page. Then, install with `npm install @serverless-chrome/lambda --ignore-scripts`. Then, extract the contents of the zip file into `your-project/node_modules/@serverless-chrome/lambda/dist`.

**Comment by andyevansweather** [comment]
Hi @adieuadieu thanks for getting back to me.

Yes, I do have some errors and they start with scripts/postinstall.js

Here is the start of the stack trace:

Downloading precompiled headless Chromium binary (stable channel) for AWS Lambda.
{ Error: connect ECONNREFUSED 192.30.XXX.113:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.30.XXX.113',
  port: 443 }

I'll try the process manually too, thanks for the tips.

**Comment by vdo2000** [comment]
@andyevansweather @adieuadeiu 

I get a similar error:
Downloading precompiled headless Chromium binary (stable channel) for AWS Lambda.
{ Error: connect ETIMEDOUT 192.30.255.112:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.30.255.112',
  port: 443 }

I was able to get it to work by doing it outside of my corporate proxy.

I wonder if you can add support to use the environment proxy settings (proxy, http_proxy, https_proxy, etc.) I think the proxy may be the issue.
