### ISSUE TITLE
Page.printToPdf has no configuration options (paper size, orientation, margins, etc)

### ISSUE THREAD

**Issue by venkat-rg** [adieuadieu/serverless-chrome#13]
Hi,
I have been using the serverless-chrome for over a week. I have come across an issue. printPdf function doesn't allow any options. For eg: to create pdf with no margin (or margin: 0). Please help on how to get the pdf with no margin to the end of each side. 
https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF

**Comment by adieuadieu** [comment]
Hi @venkat-rg. Yes; you're absolutely right.

Headless Chrome is still rather new and currently doesn't expose any configuration options (paper size, orientation, margins, etc) for printing to PDF. The good news is that people on the Chromium team are working on it. You can follow their progress on pdf-options [here](https://bugs.chromium.org/p/chromium/issues/detail?id=603559). There's a pending code-review [here](https://codereview.chromium.org/2829973002/). Once this is merged, hopefully we'll get some options to control margins, etc. 

You can get some sense of the what the configuration options will be from the modifications to the Chrome Debugging Protocol [here](https://codereview.chromium.org/2829973002/patch/200001/210021).

**Comment by venkat-rg** [comment]
Thanks for quick help.

**Comment by adieuadieu** [comment]
@venkat-rg Looks like the code has been merged. I've updated the chromium headless shell in this repository to the latest. It looks like the DevTools API documentation for [Page.printToPDF](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF) has also been updated. You can now use these options.

Closed by #14
