### ISSUE TITLE
Add support for node8.10 Lambda runtime to Serverless plugin

### ISSUE THREAD

**Issue by adieuadieu** [adieuadieu/serverless-chrome#130]
AWS [added support](https://aws.amazon.com/blogs/compute/node-js-8-10-runtime-now-available-in-aws-lambda/) for Node 8.10 runtime. :tada:

Duplicate and modify/adapt for Node 8 [wrapper-aws-nodejs6.10.js](https://github.com/adieuadieu/serverless-chrome/blob/master/packages/serverless-plugin/src/wrapper-aws-nodejs6.10.js) --> wrapper-aws-nodejs8.10.js

**Comment by necevil** [comment]
Looking forward to this when you get done @adieuadieu!

**Comment by adieuadieu** [comment]
Released in [v1.0.0-45](https://github.com/adieuadieu/serverless-chrome/releases/tag/v1.0.0-45)
