### ISSUE TITLE
@serverless-chrome/lambda encountering net::ERR_INSUFFICIENT_RESOURCES errors in versions above 1.0.0-38 while loading scripts/fonts/css

### ISSUE THREAD

**Issue by srihari93** [adieuadieu/serverless-chrome#132]
This could be a bug upstream.
Would appreciate a work around for a temporary fix.

```
\\ the load-fail event
{ method: 'Network.loadingFailed',
params: 
{ requestId: '12.1',
timestamp: 2438.844368,
type: 'Font',
errorText: 'net::ERR_INSUFFICIENT_RESOURCES',
canceled: false } 
}

\\ its response-received event
{ method: 'Network.responseReceived',
params: 
{ requestId: '12.1',
loaderId: '8792DFA0E7823FF1218163603A2EC43A',
timestamp: 2438.844087,
type: 'Font',
response: 
{ url: 'https://fonts.gstatic.com/s/opensans/v15/cJZKeOuBrn4kERxqtaUH3aCWcynf_cDxXwCLxiixG1c.ttf',
status: 200,
statusText: '',
headers: [Object],
mimeType: 'font/ttf',
requestHeaders: [Object],
connectionReused: false,
connectionId: 9,
remoteIPAddress: '216.58.211.163',
remotePort: 443,
fromDiskCache: false,
fromServiceWorker: false,
encodedDataLength: 332,
timing: [Object],
protocol: 'h2',
securityState: 'secure',
securityDetails: [Object] },
frameId: '10EBE228849E0AC2C39E3C70643F45F' } }

\\its request
{ method: 'Network.requestWillBeSent',
params: 
{ requestId: '12.1',
loaderId: '8792DFA0E7823FF1218163603A2EC43A',
documentURL: 'about:blank',
request: 
{ url: 'https://fonts.gstatic.com/s/opensans/v15/cJZKeOuBrn4kERxqtaUH3aCWcynf_cDxXwCLxiixG1c.ttf',
method: 'GET',
headers: [Object],
mixedContentType: 'none',
initialPriority: 'VeryHigh',
referrerPolicy: 'no-referrer-when-downgrade' },
timestamp: 2438.800811,
wallTime: 1523612681.8526,
initiator: { type: 'parser', url: 'about:blank', lineNumber: 204 },
type: 'Font',
frameId: '10EBE228849E0AC2C39E3C70643F45F' } }
```

This errors are not seen with the `@serverless-chrome/lambda@1.0.0-38` but are happenning when I set HTML using `Page.setDocumentContent` in recent versions.

I am attaching the [HTML as a txt](https://github.com/adieuadieu/serverless-chrome/files/1906832/jaffa.txt) that is encountering the problem as well.

My lambda which is triggering the errors looks like this
```
const chromeParams = {
    flags: [
        '--window-size=595x842',
        '--hide-scrollbars'
    ]
};
const chrome = await launchChrome(chromeParams);

const tab = await CDP.New();
const client = await CDP({
    target: tab.id
});


const {
    Page,
    Animation,
    Network
} = client;
await Page.enable();
await Animation.enable();
await Network.enable();

const pageContent = Page.getResourceTree();

const htmlOptions = {
    frameId: pageContent.frameTree.frame.id,
    html: HTML
};
await Page.setDocumentContent(htmlOptions);

await Page.loadEventFired();
```

**Comment by srihari93** [comment]
@apokryfos I had no problems with the HTML when I tried this locally on headless chrome for mac os. Everything worked as I expected it to. But, I encounter this after I deploy to lambda.

**Comment by apokryfos** [comment]
@srihari93  Yes this is exactly what I am experiencing too. In fact I am using Ubuntu 16.04 and am able to run the actual binary that then gets uploaded to lambda. 
The binary is working fine in on Ubuntu, but does not work on Lambda. 

It seems to be something introduced in Chromium 65+

**Comment by Bnaya** [comment]
hey :)
Any success overcoming this issue?

**Comment by srihari93** [comment]
@Bnaya The only way around so far is to use the older version `@serverless-chrome/lambda@1.0.0-38`. Unfortunately, I do not have the resources and time to invest more than filing this issue.

**Comment by Bnaya** [comment]
i've trying to create a failing test case
https://github.com/adieuadieu/serverless-chrome/pull/135
But i've encountered 2 problems. the test won't run npm install (need to figure where to add it)
And the test is on lambci docker, and not a real lambda. its very possible it will work there.

**Comment by Bnaya** [comment]
Update:
I've checked and found that adding `--disable-dev-shm-usage` arg fixing this issue

**Comment by apokryfos** [comment]
@Bnaya Yes that does seem to work for me as well . That's great news !

**Comment by adieuadieu** [comment]
`--disable-dev-shm-usage` was added in [v1.0.0-45](https://github.com/adieuadieu/serverless-chrome/releases/tag/v1.0.0-45). @srihari93 does it resolve your issue?

**Comment by adieuadieu** [comment]
Closing as I believe the issue has been resolved.
