### ISSUE TITLE
Can't deploy Serverless Example Service to AWS because file is too big

### ISSUE THREAD

**Issue by chug2k** [adieuadieu/serverless-chrome#137]
How can I deploy the examples (using `npm run deploy` or `serverless deploy`? I get an error about sizes being too big. I removed the `ava` package, but my zip file is still 114 mb. I get errors about the 250MB uncompressed limit. 

>  An error occurred while provisioning your stack: ScreenshotLambdaFunction - Unzipped size must be smaller than 262144000 bytes (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException....)

**Comment by bytespider** [comment]
Have you tried `npm prune --production` ?

**Comment by chug2k** [comment]
```
removed 29 packages in 9.954s`.  
```
Cool!
```
 Can't resolve 'chrome-remote-interface'
```
argh.

I should close this issue - strangely, when I build from the serverless create command (that should be updated in the documentation) it builds okay. But when I `git clone` from the repo and go to examples/aws, and run serverless deploy, I get the above.
