### ISSUE TITLE
Getting Blank Screen and no page source

### ISSUE THREAD

**Issue by romariolopezc** [adieuadieu/serverless-chrome#138]
Cannot load pages.

```
HeadlessChromium: v1.0.0-46 stable
ChromeDriver: 2.38
SeleniumWebdriver: 4.0.0-alpha.1
```

When I take a screenshot is blank and the page source is:
```html
<html xmlns="http://www.w3.org/1999/xhtml"><head></head><body></body></html>
```

**Comment by adieuadieu** [comment]
Perhaps there are some solutions in this thread: https://github.com/adieuadieu/serverless-chrome/issues/133#issuecomment-382743975
