### ISSUE TITLE
Is there a way to pin a version for Chrome using serverless-plugin-chrome?

### ISSUE THREAD

**Issue by alanhoff** [adieuadieu/serverless-chrome#142]
I'm using `serverless-plugin-chrome` directly but it looks it downloads never versions of Chrome even if I don't upgrade `serverless-plugin-chrome` itself. 

Is there a way to specify ou pin Chrome's version?

**Comment by adieuadieu** [comment]
Hm.. The version that's downloaded should be pinned to the version of the package that you're installing. For example, `serverless-plugin-chrome@1.0.0-49` will install `@serverless-chrome/lambda@1.0.0-49`.

https://github.com/adieuadieu/serverless-chrome/blob/93f03eccee3be8e283f0a9b0a375186664f2eb40/packages/lambda/scripts/postinstall.js#L72-L74

https://github.com/adieuadieu/serverless-chrome/blob/93f03eccee3be8e283f0a9b0a375186664f2eb40/packages/serverless-plugin/package.json#L42-L43
