### ISSUE TITLE
1.0.0-50 dev channel broken?

### ISSUE THREAD

**Issue by apokryfos** [adieuadieu/serverless-chrome#147]
I have tried running:
```
./headless-chromium --headless --disable-gpu --window-size=1280,1696 --no-sandbox --user-data-dir=/tmp/user-data --enable-logging --log-level=0 --v=99 --single-process --data-path=/tmp/data-path --ignore-certificate-errors --homedir=/tmp --disk-cache-dir=/tmp/cache-dir --hide-scrollbars --disable-setuid-sandbox --disable-extensions
```
and I am getting 

```
Received signal 11 SEGV_MAPERR 000000000000
#0 0x000003c4076c <unknown>
#1 0x000003c402d1 <unknown>
#2 0x7faf3b88d890 <unknown>
#3 0x7faf3a194646 <unknown>
#4 0x00000497b388 <unknown>
#5 0x00000497ae5a <unknown>
#6 0x000004a02998 <unknown>
#7 0x000003bd3729 <unknown>
#8 0x000003bd0fd7 <unknown>
#9 0x000003bd1527 <unknown>
#10 0x000003c51909 <unknown>
#11 0x000003bea185 <unknown>
#12 0x00000370e194 <unknown>
#13 0x00000370df53 <unknown>
#14 0x0000037106a2 <unknown>
#15 0x000003c62fef <unknown>
#16 0x000003ba6162 <unknown>
#17 0x000004d62eda <unknown>
#18 0x000003b9eb64 <unknown>
#19 0x000003c61fe8 <unknown>
#20 0x000003c62078 <unknown>
#21 0x000003bb4ffd <unknown>
#22 0x7faf3a104b97 __libc_start_main
#23 0x00000247602a _start
  r8: 0000000000000000  r9: 00002504e7338be8 r10: 00002504e71c3a80 r11: 0000000000000000
 r12: 00007ffe81806840 r13: 00002504e720d100 r14: 00002504e720d488 r15: 00002504e722a2c0
  di: 0000000000000000  si: 0000000000000000  bp: 00007ffe818069a0  bx: 0000000000000000
  dx: 0000000006bd7d90  ax: 0000000000000000  cx: 0000000000000000  sp: 00007ffe81806718
  ip: 00007faf3a194646 efl: 0000000000010293 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

Is the current dev channel release broken or am I just doing something completely wrong? I do expect the dev channel to push out some garbage now and then I just need to know if there's something that I'm doing completely wrong here. 

Note: Beta and stable channels are working just fine.

**Comment by adieuadieu** [comment]
Hi @apokryfos — I don't know. There is a very basic test that each build is run through before being published. Albeit, this test is performed via Docker with a amazonlinux docker image, and not directly on Lambda.

https://github.com/adieuadieu/serverless-chrome/blob/6c07eceab542c7b49fddeef78ccdfbdbda7e8de5/scripts/docker-build-image.sh#L55-L79

However.... If the dev channel release continues to be broken (have you tried with 1.0.0-51?), then it's probably a warning sign that something has changed and that the beta channel and eventually the stable channel may break soon....

**Comment by apokryfos** [comment]
@adieuadieu  Yes I can get the same issue in 1.0.0-51 . Not sure if it is relevant but it works if I remove the `--single-process` flag however (I think) that's required to run under lambda (is it? I may be wrong).

**Comment by adieuadieu** [comment]
Hm.. Interesting. Thanks. Could be that the `--single-process` flag is no longer required.. Or something else about the inter-process IPC stuff in Chromium changed. Needs further investigation..

**Comment by apokryfos** [comment]
Is there any update on this? Things work without `--single-process` on docker but unfortunately not on Lambda itself, it does not crash on lambda but it does not load any pages either (still trying to figure out what is going wrong as I'm having some difficulty grabbing logs about what is happening).

I can't be the only one that's experiencing this am I? If it helps I'm using the node8.10 lambda runtime and docker image. Haven't tested it on 6.10 though.

**Comment by apokryfos** [comment]
This seems to be the same as #168 and #170
