### ISSUE TITLE
Error while building webpack module

### ISSUE THREAD

**Issue by rutujadahatonde** [adieuadieu/serverless-chrome#148]
I am trying to run "serverless-deploy" command, but following error is displayed:

Serverless: Injecting Headless Chrome...
Serverless: WARNING: More than one matching handlers found for 'src/handlers/screenshot'. Using 'src/handlers/screenshot.js'.
Serverless: WARNING: More than one matching handlers found for 'src/handlers/pdf'. Using 'src/handlers/pdf.js'.
Serverless: Bundling with Webpack...
Time: 3589ms
                            Asset    Size  Chunks                    Chunk Names
              src/handlers/pdf.js  430 kB       0  [emitted]  [big]  src/handlers/pdf
       src/handlers/screenshot.js  412 kB       1  [emitted]  [big]  src/handlers/screenshot
          src/handlers/version.js  409 kB       2  [emitted]  [big]  src/handlers/version
    src/handlers/requestLogger.js  409 kB       3  [emitted]  [big]  src/handlers/requestLogger
          src/handlers/pdf.js.map  540 kB       0  [emitted]         src/handlers/pdf
   src/handlers/screenshot.js.map  515 kB       1  [emitted]         src/handlers/screenshot
      src/handlers/version.js.map  510 kB       2  [emitted]         src/handlers/version
src/handlers/requestLogger.js.map  511 kB       3  [emitted]         src/handlers/requestLogger
   [0] ./node_modules/@serverless-chrome/lambda/dist/bundle.es.js 12.8 kB {0} {1} {2} {3} [built]
   [2] external "http" 42 bytes {0} {1} {2} {3} [not cacheable]
  [20] external "fs" 42 bytes {0} {1} {2} {3} [not cacheable]
  [45] ./.build/src/handlers/version.js 668 bytes {2} [built]
  [46] ./.build/src/handlers/nwavy5jtr5___version.js 669 bytes {2} [built]
  [47] ./.build/src/handlers/loiolrng65f___version.js 668 bytes {2} [built]
  [59] ./.build/src/handlers/requestLogger.js 675 bytes {3} [built]
  [60] ./.build/src/handlers/g2gy6mt1z2f___requestLogger.js 675 bytes {3} [built]
  [61] ./.build/src/handlers/3hziw4sf2mj___requestLogger.js 675 bytes {3} [built]
  [72] ./.build/src/handlers/screenshot.js 672 bytes {1} [built]
  [73] ./.build/src/handlers/me21gucrlmg___screenshot.js 672 bytes {1} [built]
  [74] ./.build/src/handlers/uyqttw7xiag___screenshot.js 671 bytes {1} [built]
  [86] ./.build/src/handlers/pdf.js 664 bytes {0} [built]
  [87] ./.build/src/handlers/uegaczxyh2___pdf.js 665 bytes {0} [built]
  [88] ./.build/src/handlers/6jeqkkwtrm8___pdf.js 665 bytes {0} [built]
    + 113 hidden modules

WARNING in ./node_modules/ws/lib/BufferUtil.js
Module not found: Error: Can't resolve 'bufferutil' in '/home/rutuja/projects/spikes/headlessChrome/serverless-chrome/examples/serverless-framework/aws/node_modules/ws/lib'
 @ ./node_modules/ws/lib/BufferUtil.js 35:21-42
 @ ./node_modules/ws/lib/Receiver.js
 @ ./node_modules/ws/index.js
 @ ./node_modules/chrome-remote-interface/lib/chrome.js
 @ ./node_modules/chrome-remote-interface/index.js
 @ ./.build/src/handlers/zb7pai7y1km___requestLogger.js
 @ ./.build/src/handlers/k7jbx8o2kql___requestLogger.js
 @ ./.build/src/handlers/4vjcqkwr6wl___requestLogger.js
 @ ./.build/src/handlers/mts9tca05u___requestLogger.js
 @ ./.build/src/handlers/8bqdlgx60yu___requestLogger.js
 @ ./.build/src/handlers/63ruhasdl3s___requestLogger.js
 @ ./.build/src/handlers/el6y02lx9cs___requestLogger.js
 @ ./.build/src/handlers/viilv16n9vf___requestLogger.js
 @ ./.build/src/handlers/gt1nix4i5e___requestLogger.js
 @ ./.build/src/handlers/lt92urasqyl___requestLogger.js
 @ ./.build/src/handlers/3hziw4sf2mj___requestLogger.js
 @ ./.build/src/handlers/g2gy6mt1z2f___requestLogger.js
 @ ./.build/src/handlers/requestLogger.js

WARNING in ./node_modules/@serverless-chrome/lambda/dist/bundle.es.js
Module not found: Error: Can't resolve 'chrome-launcher' in '/home/rutuja/projects/spikes/headlessChrome/serverless-chrome/examples/serverless-framework/aws/node_modules/@serverless-chrome/lambda/dist'
 @ ./node_modules/@serverless-chrome/lambda/dist/bundle.es.js 331:52-78
 @ ./.build/src/handlers/requestLogger.js

WARNING in ./node_modules/ws/lib/Validation.js
Module not found: Error: Can't resolve 'utf-8-validate' in '/home/rutuja/projects/spikes/headlessChrome/serverless-chrome/examples/serverless-framework/aws/node_modules/ws/lib'
 @ ./node_modules/ws/lib/Validation.js 10:22-47
 @ ./node_modules/ws/lib/Receiver.js
 @ ./node_modules/ws/index.js
 @ ./node_modules/chrome-remote-interface/lib/chrome.js
 @ ./node_modules/chrome-remote-interface/index.js
 @ ./.build/src/handlers/zb7pai7y1km___requestLogger.js
 @ ./.build/src/handlers/k7jbx8o2kql___requestLogger.js
 @ ./.build/src/handlers/4vjcqkwr6wl___requestLogger.js
 @ ./.build/src/handlers/mts9tca05u___requestLogger.js
 @ ./.build/src/handlers/8bqdlgx60yu___requestLogger.js
 @ ./.build/src/handlers/63ruhasdl3s___requestLogger.js
 @ ./.build/src/handlers/el6y02lx9cs___requestLogger.js
 @ ./.build/src/handlers/viilv16n9vf___requestLogger.js
 @ ./.build/src/handlers/gt1nix4i5e___requestLogger.js
 @ ./.build/src/handlers/lt92urasqyl___requestLogger.js
 @ ./.build/src/handlers/3hziw4sf2mj___requestLogger.js
 @ ./.build/src/handlers/g2gy6mt1z2f___requestLogger.js
 @ ./.build/src/handlers/requestLogger.js

ERROR in ./.build/src/handlers/zb7pai7y1km___requestLogger.js
Module not found: Error: Can't resolve './src/utils' in '/home/rutuja/projects/spikes/headlessChrome/serverless-chrome/examples/serverless-framework/aws/.build/src/handlers'
 @ ./.build/src/handlers/zb7pai7y1km___requestLogger.js 11:13-35
 @ ./.build/src/handlers/k7jbx8o2kql___requestLogger.js
 @ ./.build/src/handlers/4vjcqkwr6wl___requestLogger.js
 @ ./.build/src/handlers/mts9tca05u___requestLogger.js
 @ ./.build/src/handlers/8bqdlgx60yu___requestLogger.js
 @ ./.build/src/handlers/63ruhasdl3s___requestLogger.js
 @ ./.build/src/handlers/el6y02lx9cs___requestLogger.js
 @ ./.build/src/handlers/viilv16n9vf___requestLogger.js
 @ ./.build/src/handlers/gt1nix4i5e___requestLogger.js
 @ ./.build/src/handlers/lt92urasqyl___requestLogger.js
 @ ./.build/src/handlers/3hziw4sf2mj___requestLogger.js
 @ ./.build/src/handlers/g2gy6mt1z2f___requestLogger.js
 @ ./.build/src/handlers/requestLogger.js
 
  Error --------------------------------------------------
 
  Webpack compilation error, see above
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.9.4
     Serverless Version:     1.29.0

and following is the snapshot of debug logs:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'deploy' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle @serverless-chrome/example-serverless-framework-aws@1.0.0-50~predeploy: @serverless-chrome/example-serverless-framework-aws@1.0.0-50
6 info lifecycle @serverless-chrome/example-serverless-framework-aws@1.0.0-50~deploy: @serverless-chrome/example-serverless-framework-aws@1.0.0-50
7 verbose lifecycle @serverless-chrome/example-serverless-framework-aws@1.0.0-50~deploy: unsafe-perm in lifecycle true
8 verbose lifecycle @serverless-chrome/example-serverless-framework-aws@1.0.0-50~deploy: PATH: /usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/node-gyp-bin:/home/rutuja/projects/spikes/headlessChrome/serverless-chrome/examples/serverless-framework/aws/node_modules/.bin:~/.local/bin:~/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/opt/arcanist/bin/:/home/rutuja/.npm-packages/bin:/home/rutuja/.local/bin:/home/rutuja/bin:/home/rutuja/.npm-packages/bin
9 verbose lifecycle @serverless-chrome/example-serverless-framework-aws@1.0.0-50~deploy: CWD: /home/rutuja/projects/spikes/headlessChrome/serverless-chrome/examples/serverless-framework/aws
10 silly lifecycle @serverless-chrome/example-serverless-framework-aws@1.0.0-50~deploy: Args: [ '-c', 'serverless deploy -v' ]
11 silly lifecycle @serverless-chrome/example-serverless-framework-aws@1.0.0-50~deploy: Returned: code: 1  signal: null
12 info lifecycle @serverless-chrome/example-serverless-framework-aws@1.0.0-50~deploy: Failed to exec deploy script
13 verbose stack Error: @serverless-chrome/example-serverless-framework-aws@1.0.0-50 deploy: `serverless deploy -v`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @serverless-chrome/example-serverless-framework-aws@1.0.0-50
15 verbose cwd /home/rutuja/projects/spikes/headlessChrome/serverless-chrome/examples/serverless-framework/aws
16 verbose Linux 4.15.4-300.fc27.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "deploy"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error @serverless-chrome/example-serverless-framework-aws@1.0.0-50 deploy: `serverless deploy -v`
22 error Exit status 1
23 error Failed at the @serverless-chrome/example-serverless-framework-aws@1.0.0-50 deploy script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Can anyone help me out in this?

**Comment by nerdmax** [comment]
+1

**Comment by uzhas-sovka** [comment]
I have the the same error near `bufferutil`. The file exists and It's `BufferUtil`, maybe this is the case?

**Comment by SidneyNemzer** [comment]
The bufferutils error is kind of a misdirection, you can see webpack actually reports it as a WARNING, not an ERROR. The real ERROR is below it.

```
ERROR in ./.build/src/handlers/zb7pai7y1km___requestLogger.js
Module not found: Error: Can't resolve './src/utils' in '/home/rutuja/projects/spikes/headlessChrome/serverless-chrome/examples/serverless-framework/aws/.build/src/handlers'
```

So @rutujadahatonde you should check your `requestLogger` file because it seems it's importing `./src/utils` but that's not a file or module.

@nerdmax and @uzhas-sovka I highly doubt your error is exactly the same, you should closely read the output to see if you can find the cause!
