### ISSUE TITLE
Error on deploy after "Serverless: Injecting Headless Chrome..."

### ISSUE THREAD

**Issue by garethmcc** [adieuadieu/serverless-chrome#155]
I am getting an error on deployment of the service right after the info `Serverless: Injecting Headless Chrome...`. Error is:
```
Error --------------------------------------------------

  ENOENT: no such file or directory, unlink '/home/user/application/service/.build/handler.js'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------
```

There is no .build or handler.js and I have no idea why it would assume that there is as there is zero configuration to that effect.

**Comment by kevinkimball** [comment]
I'm seeing this as well, but it started after my project was working previously. Any ideas?

**Comment by kevinkimball** [comment]
Appears related to: https://github.com/serverless/serverless/issues/3993 possibly a permissions error?

**Comment by kevinkimball** [comment]
I was able to fix this in a weird way:  I was exporting multiple handlers from my `index.js` file in the root of the directory. By breaking them up into multiple files and using `handlers/file.default` as the handler, it started working. I think this is related to something weird going on in the build step. 🤷‍♂️

**Comment by Maxwell2022** [comment]
I have the exact same issue after installing `serverless-plugin-chrome`, tried to split my handlers into separate files as you mention and still have the same error coming up. Commenting out the `serverless-plugin-chrome` plugin and my serverless functions are starting so definitely coming from this plugin. Maybe a version incompatibility? 

`serverless 1.28.0` & `serverless-plugin-chrome 1.0.0-55`

**Comment by Maxwell2022** [comment]
> Appears related to: [serverless/serverless#3993](https://github.com/serverless/serverless/issues/3993) possibly a permissions error?

I don't think it's related, I'm trying to run it locally with serverless offline and I have the same issue. my error message is not on the unlink but link:

```
Serverless: Injecting Headless Chrome...

  Error --------------------------------------------------

  ENOENT: no such file or directory, link '/app/.build/src/handlers/graphql.js' -> '/app/.build/src/handlers/npabhq08rf___graphql.js'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```

**Comment by JoanEspasa** [comment]
Sorry for ressurecting this, but I only have one function on the lambda and I'm affected with the same issue. Any updates on this?

**Comment by juancarlosfarah** [comment]
I'm running into the same issue. I see it running `serverless-offline`. If I add enable Chrome in more than one function (under the `custom` block), I get the same error.

```
custom:
  # chrome plugin only enabled for these functions
  chrome:
    functions:
      - function1
      - function2
```

The above configuration will output:

```
  Error --------------------------------------------------

  ENOENT: no such file or directory, unlink '/.../.build/dist/index.js'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------
```

If I only leave one function:

```
custom:
  # chrome plugin only enabled for these functions
  chrome:
    functions:
      - function1
```

The app starts, but the other function I left out (function2), will be removed from the handler.

**Comment by kaviyarasu7** [comment]
Any updates on this issue

**Comment by amesas** [comment]
Same problem here.
If I enabled serverless-plugin-chrome i have to export functions in different handlers.

**Comment by bobylito** [comment]
Hey, I'm also facing the issue. I moved forward with the suggestion from @juancarlosfarah and after I faced this:

> The app starts, but the other function I left out (function2), will be removed from the handler.

Which I resolved using:
```yaml
package:
  include:
    - myHandlersFolder/**
```

Hope it helps :)

**Comment by erdahuja** [comment]
Any updates?

**Comment by aymericbouzy** [comment]
might be because of https://github.com/adieuadieu/serverless-chrome/blob/2faa7772e9136055f56f629aa88304cf229a36c6/packages/serverless-plugin/src/index.js#L3 ?

**Comment by zolbayars** [comment]
After hours of trying, I've resolved this issue by creating a whole new service with only one function and endpoint in it. Don't know why it worked.
