### ISSUE TITLE
Issue getting proxy settings to work with Python/Selenium

### ISSUE THREAD

**Issue by anshajgoel** [adieuadieu/serverless-chrome#157]
### I want to scrape a webpage through selenium using a proxy which uses a login and password but when I add proxy settings to it, its not accepting them.

**Following is my code:**
`from selenium import webdriver`
`from selenium.webdriver.common.proxy import Proxy, ProxyType`
`from selenium.webdriver.chrome.options import Options`
`from selenium.webdriver.common.proxy import *`

`PROXY = "http://proxy.com:port/"`
`proxy = Proxy()`
`proxy.http_proxy = PROXY`
`proxy.ftp_proxy = PROXY`
`proxy.sslProxy = PROXY`
`proxy.proxy_type = ProxyType.MANUAL`
`proxy.socksUsername = 'username'`
`proxy.socksPassword = "password"`
`capabilities = webdriver.DesiredCapabilities.CHROME`
`proxy.add_to_capabilities(capabilities)`

`chrome_options = webdriver.ChromeOptions()`
`chrome_options.add_argument('--headless')`
`chrome_options.add_argument('--no-sandbox')`
`chrome_options.add_argument('--disable-gpu')`
`chrome_options.add_argument('--window-size=1280x1696')`
`chrome_options.add_argument('--user-data-dir=/tmp/user-data')`
`chrome_options.add_argument('--hide-scrollbars')`
`chrome_options.add_argument('--enable-logging')`
`chrome_options.add_argument('--log-level=0')`
`chrome_options.add_argument('--v=99')`
`chrome_options.add_argument('--single-process')`
`chrome_options.add_argument('--data-path=/tmp/data-path')`
`chrome_options.add_argument('--ignore-certificate-errors')`
`chrome_options.add_argument('--homedir=/tmp')`
`chrome_options.add_argument('--disk-cache-dir=/tmp/cache-dir')`
`chrome_options.add_argument('--ignore-certificate-errors')`
`chrome_options.binary_location = os.getcwd() + "/bin/headless-chromium"`

`driver = webdriver.Chrome(desired_capabilities=capabilities, chrome_options=chrome_options)`
`driver.get("http://www.showmyip.gr/")`
`print(driver.page_source)`

It prints the webpage with my local IP.

Also, If there is anything wrong in this code, please do let me know.
Thanks!

**Comment by muvera** [comment]
I have the same question. Let me know if you have figured out. Thanks

**Comment by saikeerthi12** [comment]
sorry it is not working

**Comment by legut2** [comment]
I am able to get headless chrome running through a proxy service but I am unable to get headless-chromium to go through a proxy.

**Comment by legut2** [comment]
I comment/uncomment the following line to use either chrome or headless-chromium: `chrome_options.binary_location = os.getcwd() + "/headless-chromium"`

Running the same proxy snippet will yield either the source I want to get to with regular chrome and the proxy will work. However when using headless-chromium I get the following source printed: 
`<html xmlns="http://www.w3.org/1999/xhtml"><head></head><body></body></html>`

The proxy works with chrome but not this headless-chromium. Any thoughts or ideas on what to try? @adieuadieu 

I have tried it with:

headless chrome= 62.0.3202.94
chromedriver= 2.32.498513
and
headless chrome= 69.0.3497.81
chromedriver= 2.44
