### ISSUE TITLE
Option to set custom header and footer in chrome

### ISSUE THREAD

**Issue by venkat-rg** [adieuadieu/serverless-chrome#16]
Hi, 

Is there a way to set markup in chrome as header/footer during pdf generation in chrome. Thanks In Advance.

**Comment by adieuadieu** [comment]
Hi @venkat-rg,

That is a little bit out of scope for _serverless-chrome_ as this project's goal is just to provide you with everything you need to run Chrome in Lambda. What the developer does from there is up to them. I am working on another project built on _serverless-chrome_, [serverless-pdf](https://github.com/adieuadieu/serverless-pdf) which does pdf-y stuff related to your question. However, so far I've not implemented any header/footer functionality.

The DevTools procol for interacting with headless Chrome does have a [`displayHeaderFooter`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF) parameter which will cause the page's title and page numbers to be printed to the PDF. However, if your goal is to have a piece of HTML/CSS content repeated on every printed page, you would need to implement that within the DOM of the page you're printing to PDF. This is untested/pseudo-code, but something like:

```html
<html>
<head>
  <style type="text/css">
    .printable {
      display: none;
    }

    @media print {
      .printable {
        display: block;
      }

      section {
        page-break-after: always;
        page-break-inside: avoid;
      }
    }
  </style>
</head>
<body>
  <!-- page 1 -->
  <section>
    <header class="printable">
      My custom header
    </header>

    <div>Main page 1 content</div>

    <footer class="printable">
      My custom footer
    </footer>
  </section>

  <!-- page 2 -->
  <section>
    <header class="printable">
      My custom header
    </header>

    <div>Main page 2 content</div>

    <footer class="printable">
      My custom footer
    </footer>
  </section>

  <!-- page 3 -->
  <section>
    <header class="printable">
      My custom header
    </header>

    <div>Main page 3 content</div>

    <footer class="printable">
      My custom footer
    </footer>
  </section>
</body>
</html>
```
