### ISSUE TITLE
Lambda exit without error when generating large PDF files

### ISSUE THREAD

**Issue by Maratyz** [adieuadieu/serverless-chrome#162]
In AWS lambda function environment, the printToPDF function cannot finish when large html, e.g. > 200 pages is fetched. The PDF file for the same page can be generated when triggered in local environment (serverless invoke or AWS SAM). 

I have contacted AWS support who acknowledged that it attributes to environment issues. However, AWS does not have the responsibilities to investigate the library though. Our investigation is still ongoing. 

the chrome-err.log shows
```
Received signal 7 BUS_ADRERR 
...(stack trace)...
Calling _exit(1). Core file will not be generated.
```

It is confirmed that `--disable-dev-shm-usage` has been flagged.

Library Version 
    "serverless": "^1.24.1",
    "serverless-plugin-chrome": "1.0.0-53",
    "serverless-webpack": "4.0.0",
    "chrome-remote-interface": "0.25.3"

**Comment by adieuadieu** [comment]
Does the Lambda function have enough memory?

**Comment by Maratyz** [comment]
Yes, the lambda function has been allocated with the maximum memory (3008MB) and the report shows that the maximum memory usage is less than 1GB

**Comment by Maratyz** [comment]
Hi @adieuadieu, Here's an investigation from AWS. 

It turned out that chromeheadless attempts to write a big chunk in /tmp folder when attempting to generate a large PDF file. As a result, the lambda execution is terminated since it exhausts the 512MB /tmp disk space.

So far, we have not come up with a better solution besides moving it to a container.
