### ISSUE TITLE
serverless-chrome/lambda readme example is missing install of 'chrome-remote-interface'

### ISSUE THREAD

**Issue by renschler** [adieuadieu/serverless-chrome#169]
I was trying to get started by following the readme here: https://github.com/adieuadieu/serverless-chrome/tree/master/packages/lambda

I created a new function by copying the code provided and when I went to run it I got an error saying 'chrome-remote-interface' was not available.

After running `npm install chrome-remote-interface` and rezipping+uploading my deployment package, the lambda function now completes.

We just need to update the readme accordingly.

**Comment by sepulworld** [comment]
$ sls invoke --function test_chrome_headless
```
{
    "errorMessage": "Cannot find module 'chrome-remote-interface'",
    "errorType": "Error",
    "stackTrace": [
        "Function.Module._load (module.js:474:25)",
        "Module.require (module.js:596:17)",
        "require (internal/module.js:11:18)",
        "Object.<anonymous> (/var/task/p7aihhqnngp5sdbntmv89qkt9___test_chrome_headless.js:1:75)",
        "Module._compile (module.js:652:30)",
        "Object.Module._extensions..js (module.js:663:10)",
        "Module.load (module.js:565:32)",
        "tryModuleLoad (module.js:505:12)",
        "Function.Module._load (module.js:497:3)"
    ]
}
```

I have a similar issue as well. However, `npm install chrome-remote-interface` didn't seem to fix the issue for me.  

I see `Serverless: Excluding development dependencies...` in the sls deploy output. I wonder if it isn't packaging everything up?

**Comment by sepulworld** [comment]
Ah, so I had to move chrome-remote-interface out of devDependencies into dependencies like how it is in the example package.json...

https://github.com/adieuadieu/serverless-chrome/blob/master/examples/serverless-framework/aws/package.json#L46-L48
