### ISSUE TITLE
serverless-chrome as micro-service inside a project

### ISSUE THREAD

**Issue by Maxwell2022** [adieuadieu/serverless-chrome#174]
After reading a confusing documentation in 2 or 3 different places, I think I cannot use this plugin inside my project. I feel like my setup is a very common setup, a node API using `serverless` that I can test offline using `serverless-offline`.

The first issue I was facing (and still facing) is the link issue https://github.com/adieuadieu/serverless-chrome/issues/155 which is probably related to https://github.com/adieuadieu/serverless-chrome/issues/96

Then reading the doc, it mention that if I want to run `serverless-chrome` locally, I should use the docker image that embed chromium. However I cannot do this because I need to run my server offline and I'm already using `docker-compose` with the `node:carbon` image that I need for `serverless-offline` to work.

The only solution I can see is to compile chromium based from a node image. I'm surprised that no one talk about this. Am I getting something wrong here? From my understanding, the example is meant to be run by itself and is hard to incorporate inside an existing `serverless` project.

I'll try to spend some time building a node image that embed chromium. I think it would be very beneficial for everyone. This docker image is only use locally for development (or CI) and would be compatible for any `serverless` based on node

**Comment by Maxwell2022** [comment]
A quick update on my mission to use serverless + chromeless to generate PDFs on demand. I've ended up looking at [`puppeteer`](https://github.com/GoogleChrome/puppeteer) which install automatically chrome when installing the package. Ii can run it locally all good. However I'm already thinking that this won't work in serverless because it will install chrome on my CI agent but once in Lambda it won't work.

Apparently there is few solutions to counter this, the first one is to us a serverless-plugin (`serverless-hooks-plugin`) that can run any command when the function start, so it could run the `puppeteer` install that would install chrome.

There is also another option to host chrome on S3 and download it when the function is triggered. Check if chrome is available, if not wait for download, then do stuff.

I'm still investigating this 2 options, I'm not sure I'm going to the right direction, but at least I can now generate PDF locally using serverless

**Comment by olecom** [comment]
> mission to use serverless + chromeless to generate PDFs on demand

Hi! Had same idea: to have headless Chrome on AWS Lambda as PDF printing service.

The only thing which is really needed from this project is binary itself. After getting it, there is a simple way to bundle and update Lambda. Archived Chrome v65 has 43Mbytes size which fits into 50Mbyte limit.

1) zip everything:
```sh
    zip -9 -r "../$ZIP_FILE" *
```
2) update code:
```sh
    aws --region "$AWS_REGION" 'lambda' 'update-function-code' \
        --function-name "$LAMBDA_NAME" \
        --zip-file "fileb://../$ZIP_FILE"
```
3) run get PDF processing from e.g. `node.js` api handler by using `aws-sdk`:
```js
   Lambda.invoke({
        InvocationType: 'RequestResponse',
        FunctionName: config.AWS_PDF_FunctionName || 'newPDF-generator:Production',
        Payload: JSON.stringify({
            go: 'getPDF', docType, templateStr, jsonStr, debug
        }),
    }, (err, data) => {
...     
    }
```

Handler for Lambda:
```js

const processEvent = (event, context, callback) => {
    const go = event && event.go

    if('CDP.Version' === go){
        return CDP_Version(callback)
    }

    if('getPDF' === go){
        return getPDF.getSinglePDF(
            event.docType,
            event.templateStr,
            event.jsonStr,
            event.debug,
            context,
            (err, pdfFiles, pdfOutput, reportName) => {
...
            })
    }
}

// AWS Lambda handler
exports.handler = (event, context, callback) => {
    context.callbackWaitsForEmptyEventLoop = false

    if(!drv) return copyStuff(
        () => spawnChrome(
            err => err ? callback(err) : processEvent(
                event, context, callback
            )
        )
    )
    return processEvent(event, context, callback)
}
```

It is abstracted so get PDF itself can be run locally or offline with same api handler:
```js
    if(process.env.NODEJS_LOCAL){
        return require('./aws-newPDF/getPDF.js').getSinglePDF(docType, templateStr, jsonStr, debug, {}, requestCallback)
    }

    console.log('Lambda.invoke')

    return Lambda.invoke({

```

For local development Chrome Canary can be executed by spawned script:
```sh
#!/bin/sh

~/AppData/Local/Google/Chrome\ SxS/Application/chrome \
--no-sandbox \
--no-zygote \
--disable-dev-shm-usage \
\
--headless \
--remote-debugging-port=9222 \
--disable-gpu \
--disable-translate \
--disable-extensions \
--disable-background-networking \
--safebrowsing-disable-auto-update \
--disable-sync \
--metrics-recording-only \
--disable-default-apps \
--no-first-run \
--mute-audio \
--hide-scrollbars \
</dev/null 2>&1 | cat
```

Doing spawn of Chrome on Lambda env with some additional `$HOME` settings for correct fonts rendering (https://github.com/adieuadieu/serverless-chrome/issues/184#issuecomment-480028352) is done by script:
```sh
#!/bin/sh

set -x

export HOME=$PWD

while true
do ./headless-chromium \
--no-sandbox \
--no-zygote \
--single-process \
--disable-dev-shm-usage \
\
--headless \
--font-render-hinting \
--remote-debugging-port=9222 \
--disable-gpu \
--disable-translate \
--disable-extensions \
--disable-background-networking \
--safebrowsing-disable-auto-update \
--disable-sync \
--metrics-recording-only \
--disable-default-apps \
--no-first-run \
--mute-audio \
--hide-scrollbars \
</dev/null 1>/dev/null 2>&1 # noisy output; enable only for debug
# cleanup any core dumps
rm -f /tmp/core*
done 
```

MS Windows is used here inside git for windows mingw environment, thus shell scripting is nearly the same as it is on GNU/Linux.
