### ISSUE TITLE
Provide Chrome binary via AWS Lambda Layer

### ISSUE THREAD

**Issue by adieuadieu** [adieuadieu/serverless-chrome#177]
AWS Lambda now has support for a feature called Layers which lets one provide "layers" of sharable/reusable stuff, like binaries, e.g. like Chrome.

Use this feature to make it easier for everyone to use Chrome on AWS Lambda.

**Comment by mweberxyz** [comment]
Serverless added Layers support on launch day, so we shouldn't need to do too much heavy lifting in serverless-chrome:

https://serverless.com/framework/docs/providers/aws/guide/layers/

https://github.com/serverless/serverless/pull/5538

**Comment by mweberxyz** [comment]
@adieuadieu Do you plan to publish directly to a public layer for people to rely upon in their own projects? Relying on a hosted layer would simplify the process massively for people to get started using serverless chrome on Lambda.

**Comment by adieuadieu** [comment]
@mweberxyz Yes! Since the project already offers/provides pre-built Chromium binaries, it would be the next step in terms of convenience if those binaries are made available directly in a public layer. Would simplify the packaging pain point of the project.

**Comment by AndreaAdvanon** [comment]
Any plans on this?

**Comment by decebal** [comment]
I think this would be one example: https://github.com/brettstack/aws-serverless-website-canary/tree/master/serverless-chrome-layer
