### ISSUE TITLE
Support for Alibaba cloud function compute

### ISSUE THREAD

**Issue by paolomainardi** [adieuadieu/serverless-chrome#180]
Add support for Alibaba cloud Functions with package @serverless-chrome/aliyun-functions and appropriate headless chrome binaries, and include Dockerfile for building Chrome binary. 

Related: #43 — Support for Google Cloud Functions
Related to #44 — Support for Azure functions

**Comment by paolomainardi** [comment]
Can you point me some documentation to start to dig with it ? I think that the first step would be to know the base image used on the different runtime (starting from node) then building static libraries for it.

**Comment by cockcrow** [comment]
Here's the documentation for Alibaba Cloud Function Compute.
https://www.alibabacloud.com/help/product/50980.htm

Hope helps.
