### ISSUE TITLE
impossible to install on windows10

### ISSUE THREAD

**Issue by andreabisello** [adieuadieu/serverless-chrome#187]
on updated windows10
with updated npm
i installed serverless,
but running the serverless create command you obtain this error. I ask for a co worker to make a try on his pc, but nothing changed. 

C:\tmp\headless_test>serverless create -u https://github.com/adieuadieu/serverless-chrome/tree/master/examples/serverless-framework/aws
Serverless: Generating boilerplate...
Serverless: Downloading and installing "examples\serverless-framework\aws"...

  Serverless Error ---------------------------------------

  Error: ENOENT: no such file or directory, link 'C:\tmp\dist' -> 'C:\Users\ANDREA~1.BIS\AppData\Local\Temp\serverless-chrome\packages\lambda\integration-test\dist'

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           10.9.0
     Serverless Version:     1.35.1

**Comment by TaylorCaldwell-FiveTalent** [comment]
Experiencing the same issue - any updates on this? Have you found a way around this issue?

**Comment by Robert-Murphy** [comment]
+1. 
Seems to be a few issues raised around this Error over the last 2years but no update as of yet...
