### ISSUE TITLE
Specs don't run on fresh install of the serverless framework example

### ISSUE THREAD

**Issue by diiq** [adieuadieu/serverless-chrome#189]
Hi! thanks for making serverless-chrome -- it's a big time-saver.

I can successfully deploy and use the serverless framework example, but if I do a fresh install and try to run the tests, I cannot.

```bash
serverless create -u https://github.com/adieuadieu/serverless-chrome/tree/master/examples/serverless-framework/aws
npm install
npm run test
```

The first failure is that eslint is not listed in package.json as a dependency; so `npm run test` will fail unless it has already been installed globally. Not a big deal, but a little jarring.

Unfortunately, even if I eliminate the linting step, the tests still will not run, with ava returning the error message:

```
Unexpected Babel configuration for AVA. See https://github.com/avajs/ava#es2017-support for allowed values.
```

I've never used AVA before, and that link seems fairly unhelpful to me, but it looks like "inherit" might no longer be a valid value for AVA babel configuration?

Sorry I don't have a complete fix; but it'd be great if the tests on a fresh installation of the examples ran and passed -- especially since the contributing guidelines want 100% spec coverage before opening a PR :)

**Comment by klimesf** [comment]
I changed the `"ava"` configuration in `package.json` from

```
  "ava": {
    "require": "babel-register",
    "babel": "inherits"
  },
```

to 

```
  "ava": {
    "require": "babel-register",
    "babel": "inherit"
  },
```

and it worked. Maybe there is a typo, or maybe the option was renamed from `inherits` to `inherit`.
