### ISSUE TITLE
Windows 10 EPERM: operation not permitted, scandir

### ISSUE THREAD

**Issue by tonyschollum** [adieuadieu/serverless-chrome#192]
Once I add the ... plugin and try to deploy I get the below error, without the plugin it works fine. Any suggestions on how to get past this?

I have tried Serverless 1.35.1 & 1.36.0

serverless deploy -v
Serverless: Injecting Headless Chrome...
Serverless: Packaging service...
Serverless: Excluding development dependencies...

  Error --------------------------------------------------

  EPERM: operation not permitted, scandir 'C:\Projects\Samples\pdf\NodeJsLambda\NodeJsLambdaPdfEndPoint\.build\node_modules'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           8.11.1
     Serverless Version:     1.35.1

Thanks a lot!

**Comment by wmundev** [comment]
Hey tony, 
try this?
https://stackoverflow.com/questions/50590798/nodejs-serverless-windows-10/50613829#50613829

**Comment by thasmo** [comment]
Got a similar problem here.
```
> serverless deploy -v
Serverless: Injecting Headless Chrome...
Error --------------------------------------------------
EPERM: operation not permitted, symlink 'C:\Users\thasmo\Projects\myproject\node_modules' -> 'C:\Users\thasmo\Projects\myproject\.build\node_modules'
```
This only happens when adding the `serverless-plugin-chrome` to the serverless `plugins`. When I remove `serverless-plugin-chrome` then `serverless deploy` works.

**Comment by thasmo** [comment]
@tonyschollum, does https://github.com/adieuadieu/serverless-chrome/pull/208 fix the `scandir` permission issue for you?
