### ISSUE TITLE
Will this project work with a AWS Ubuntu 18 instance? 

### ISSUE THREAD

**Issue by vedantroy** [adieuadieu/serverless-chrome#196]
The readme indicates this project is designed to work with AWS lambda. But will it also work on an AWS EC2 instance running Ubuntu? Additionally, is it possible to use Python scripts to interact with this project, or does everything have to be done through JS?

**Comment by apokryfos** [comment]
I've used this on my own Ubuntu 18 installation and it works just fine, so I see no reason why it shouldn't work on an EC2 Ubuntu. Not sure about the python bit though.
