### ISSUE TITLE
Lambda Error

### ISSUE THREAD

**Issue by DucNguyenVan** [adieuadieu/serverless-chrome#20]
hi,
i have a problem when i run lambda many times(in my case is every 5s)
```
100.times.each {sns.publish(...) sleep(5)}   #trigger lambda
```

it through out Error
```
{
    "errorMessage": "Unable to capture screenshot",
    "errorType": "Error",
    "stackTrace": [
        "/var/task/handler.js:4084:14",
        "throw (native)",
        "step (/var/task/handler.js:759:31)",
        "/var/task/handler.js:772:14",
        "process._tickDomainCallback (internal/process/next_tick.js:135:7)"
    ]
}
```
what did i do wrong here? 
Thanks In Advance.

**Comment by adieuadieu** [comment]
Hi @DucNguyenVan. My apologies for my slow reply.

If you're using the provided sample `captureScreenshot` [handler](https://github.com/adieuadieu/serverless-chrome/blob/master/src/handlers/captureScreenshot.js#L74), there should be some additional information that gets logged. You can see these logs in [CloudWatch](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logs:). In the CloudWatch log stream for your Lambda function, you should see a log line which begins with `Error capturing screenshot for..`. This should include the URL and then the actual try-catch error message. I might be able to better help you if you can tell me what this error message says.
