### ISSUE TITLE
lambda amazon memory leak

### ISSUE THREAD

**Issue by jesuslazaro87** [adieuadieu/serverless-chrome#201]
I am running Amazon Lambda function which uses puppeteer-core first version, 1.7.0, I download the puppeteer from s3(dev-headless-chromium-70.0.3534.4-amazonlinux-2017-03.zip) and run from /tmp in lambda environment.

The problem is that the function always increments the memory usage, I close the browser in each execution. My question is, does chromium write files to the filesystem with each execution in a manner that uses more disk space?

**Comment by samikarak** [comment]
I have the same issue, the error is looking like the following

> { Error: spawn ENOMEM
>     at _errnoException (util.js:1022:11)
>     at ChildProcess.spawn (internal/child_process.js:323:11)
>     at Object.exports.spawn (child_process.js:502:9)
>     at e.exports.launch (/var/task/dist/app.js:3061:14203)
>     at <anonymous> code: 'ENOMEM', errno: 'ENOMEM', syscall: 'spawn' }

**Comment by jesuslazaro87** [comment]
> I have the same issue, the error is looking like the following
> 
> > { Error: spawn ENOMEM
> > at _errnoException (util.js:1022:11)
> > at ChildProcess.spawn (internal/child_process.js:323:11)
> > at Object.exports.spawn (child_process.js:502:9)
> > at e.exports.launch (/var/task/dist/app.js:3061:14203)
> > at  code: 'ENOMEM', errno: 'ENOMEM', syscall: 'spawn' }

Hello , the only solution that i found was move yo use the package chrome-aws-lamba, it use more memory than puppeteer package alone but is more stable, gretting
