### ISSUE TITLE
@serverless-chrome/lambda Custom font problems

### ISSUE THREAD

**Issue by ksyke** [adieuadieu/serverless-chrome#204]
Good day, this is my very first post here in github. Please excuse me if i did something wrong. 
Node: nodejs8.10

My question is quite simple. Are fonts treated differently in serverless-chrome launched in lambda than chrome launched locally (Windows10)?

These are samples of images generated from the same page.

This is from lambda:
![lambdatest](https://user-images.githubusercontent.com/50691802/57829738-86d60d00-77e2-11e9-8c0a-3d900349c07f.png)

This is done locally:
![localtest](https://user-images.githubusercontent.com/50691802/57829740-876ea380-77e2-11e9-86dd-1d21751e0843.png)

**Comment by alixaxel** [comment]
@ksyke Lambda only ships with DejaVu font face, see https://github.com/alixaxel/chrome-aws-lambda/issues/37#issuecomment-493646469

**Comment by olecom** [comment]
@ksyke if same look is needed then all used fonts should be provided into lambda execution environment for chrome, example: https://github.com/adieuadieu/serverless-chrome/issues/184#issuecomment-480028352
