### ISSUE TITLE
Error when run with webpack + typescript

### ISSUE THREAD

**Issue by trungtin** [adieuadieu/serverless-chrome#210]
```
Serverless: Injecting Headless Chrome...
ENOENT: no such file or directory, link '/.../.build/handlers/hello/index.js' -> '/.../.build/handlers/hello/ogqvbyz6zw___index.js'
```

The error is self-described, it come from this line https://github.com/adieuadieu/serverless-chrome/blob/2faa7772e9136055f56f629aa88304cf229a36c6/packages/serverless-plugin/src/utils.js#L44
Because the documentation note that the `serverless-webpack` (which I use to compile typescript) must come after this plugin, so the file it looking for is `index.ts` not `index.js`. It work fine with `serverless-plugin-typescript` because I think `serverless-plugin-typescript` must run before this.

**Comment by 592da** [comment]
Anyone got this issue solved?
Please update if so 🙏

**Comment by kaykhancheckpoint** [comment]
Have the same problem, does anyone have a solution?

**Comment by ericmaicon** [comment]
Same issue here..anyone?

**Comment by kaykhancheckpoint** [comment]
@ericmaicon I found an alternative solution if you need puppeteer which meant moving away from this library.

I setup a dedicated puppeteer lambda using the following https://github.com/alixaxel/chrome-aws-lambda

and then my typescript project would simply invoke this dedicated lambda function.
