### ISSUE TITLE
Should we need to update the supported version from node8.10 to node.10x

### ISSUE THREAD

**Issue by StephenLover** [adieuadieu/serverless-chrome#215]
Hi, first of all I would like to express my appreciation with this project, it was a really good one.

However, recently AWS made an announce that they are not going to provide any node8.x support for lambdas.

I was just wondering that if we should update this amazing library to node10.x so we can continually use it?

**Comment by Aponcher** [comment]
Bump - this will become an issue within the next few months if node 10 support isn't added soonish @adieuadieu

**Comment by adieuadieu** [comment]
Hi Adam — I intend to do a complete refresh of the project mid November.

**Comment by twhid** [comment]
@adieuadieu Greetings! 

How's the refresh coming along?

**Comment by cheryly279** [comment]
> @adieuadieu Greetings!
> 
> How's the refresh coming along?

Yes and will it work with 12.x as well as 10.x?

**Comment by sachinsmc** [comment]
Hey @adieuadieu Awaiting for this. Let us know if you need extra hands. Took fork but looks like it's gonna take a while to figure it out. Our all services are on Node10(AWS Lambda) except one which uses this package.

**Comment by belmer** [comment]
Im really excited to see support for Nodejs 10x or 12x. Right now, this is holding us off to go full Lambda. Please let us know if you need extra hands in any way. Looking forward for the new release.

**Comment by Aponcher** [comment]
hey @adieuadieu just wanted to touch base on the status of the refresh and any updated ETA

**Comment by twhid** [comment]
folks on this thread, here's an alternative: https://github.com/alixaxel/chrome-aws-lambda

**Comment by Aponcher** [comment]
@adieuadieu any update on this... starting to get down to the wire

**Comment by belmer** [comment]
It's 2020. Anytime soon?

**Comment by ortegoncarlos** [comment]
Thanks for this amazing library, but this thread is major now.

**Comment by erdahuja** [comment]
@belmer Waiting too! 
hey @adieuadieu thanks for amazing project, any updates on upgrade?

**Comment by onoranzefunebricloud** [comment]
+1

**Comment by jona** [comment]
Also looking forward to this update :)

**Comment by link365dev** [comment]
When trying to deploy the example, I got:

` Error: The "serverless-plugin-headless-chrome" plugin only supports the Node.js 6.10 or 8.10 runtimes. Your service is using the "nodejs12.x" provider.`
