### ISSUE TITLE
Unable to start chrome in AWS Lambda

### ISSUE THREAD

**Issue by anirudhmb** [adieuadieu/serverless-chrome#220]
I am able to launch chrome in local environment.
But when use the same code in the AWS environment, I encounter an error - 

`{
  "errorMessage": "Unable to start Chrome. If you have the DEBUG env variable set,there will be more in the logs.",
  "errorType": "Error",
  "stackTrace": [
    "/opt/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:376:13",
    "Generator.throw (<anonymous>)",
    "step (/opt/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:311:193)",
    "/opt/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:311:404",
    "<anonymous>",
    "process._tickDomainCallback (internal/process/next_tick.js:228:7)"
  ]
}`

**Comment by CatNinjaProgrammer** [comment]
I have the same issue as well. Not sure whats going on....

Trying to understand what line 311 is trying todo XD

```
function _asyncToGenerator$2(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { return Promise.resolve(value).then(function (value) { step("next", value); }, function (err) { step("throw", err); }); } } return step("next"); }); }; }
```

**Comment by braco** [comment]
This is still an issue, it's broken.
