### ISSUE TITLE
Unable to build chrome on aws

### ISSUE THREAD

**Issue by erdahuja** [adieuadieu/serverless-chrome#238]
Hi, i tried building the chrome locally and on ec2 as well, but it failed on both.
On ec2 the build didn't appeared in my s3. I am trying to build an old version of headless chrome to run on latest node10 environment. 
Below config:

Dockerfile 
~FROM lambci/lambda~ -> FROM lambci/lambda:build-nodejs10.x
~FROM amazonlinux:2017.03~ ->FROM amazonlinux:latest
```
docker build \  -t "headless-chromium:64.0.3264.0" \
  --build-arg VERSION="64.0.3264.0"
```

ec2 config:

```
{
  "SpotPrice": "1.3362",
  "InstanceCount": 1,
  "Type": "one-time",
  "LaunchSpecification": {
    "ImageId": "ami-8c1be5f6",
    "InstanceType": "c5.18xlarge",
    "IamInstanceProfile": {
      "Arn": "this gets updated by the ec2-build.sh script"
    },
    "BlockDeviceMappings": [
      {
        "DeviceName": "/dev/xvda",
        "Ebs": {
          "DeleteOnTermination": true,
          "VolumeType": "gp2",
          "VolumeSize": 64,
          "SnapshotId": "snap-080eb3cb2eda29974"
        }
      }
    ],
    "UserData": ""
  }
}

```
The script had a little missing arg which i added.
Logs:

https://abchromebuiid.s3-us-west-2.amazonaws.com/exportedlogs/49b9a273-d4d6-4cda-95b4-f7bb15563e9d/i-0353fd1db84225270-cloudinit-chromium-64.0.3264.0-canary/000000.gz

I can provide more if needed. Please help.

**Comment by belmer** [comment]
I don't think you can. This module does not support Node 10x or later yet.  I believe it's still on the work [In Progress](https://github.com/adieuadieu/serverless-chrome/issues/215)

**Comment by erdahuja** [comment]
Thanks @belmer i can also see that in #206 . Will wait then :)
Do you suggest using node8 for building it?
I think aws lambda will stop supporting them after dec 31st.

**Comment by belmer** [comment]
@erdahuja we are on the same boat, but we cannot afford to stop the service when aws stop supporting for node8. So I suggest you think of a back-up plan when that happens and the update will not be released before then. I was thinking to transfer the service to ec2 in the mean time. And put the result somewhere accessible by other lambda functions. S3 perhaps.

**Comment by erdahuja** [comment]
@belmer I'll wait, moving to ec2 would be too costly for my use case or will look for 3rd party chrome services.

**Comment by erdahuja** [comment]
@belmer any updates?
