### ISSUE TITLE
Need latest chrome binaries

### ISSUE THREAD

**Issue by shelgeram07** [adieuadieu/serverless-chrome#242]
Hi Team, 
Can you please provide latest chrome binaries?
Also it would be great if you can provide the corresponding chromedriver and dependencies like shared object libraries. So that all dependencies needed to run lambda are at a single place.

**Comment by jrajpal-afk** [comment]
With the same-site cookie mandate coming in, a lot of automations will fail if they are unable to upgrade to the latest chrome. Please rollout a release with the latest chromium.. :pray::skin-tone-3:

**Comment by Exid87** [comment]
Will binaries be coming out soon?

**Comment by hoangphuc50** [comment]
I got issues with the **same-site** cookie, with the website have a same-site cookie we can't log in anymore.

**Comment by adieuadieu** [comment]
New release now [available](https://github.com/adieuadieu/serverless-chrome/releases/tag/v1.0.0-57).
