### ISSUE TITLE
Impossible to get bundle under AWS size limits

### ISSUE THREAD

**Issue by onoranzefunebricloud** [adieuadieu/serverless-chrome#248]
Hi,

I have tried a lot of different ways, but just installing this serverless plugin, with no other dependencies, the bundle size goes over 300 MB (unzipped) and ~110MB zipped which is over the 250 MB of bundle in AWS Lambda.

I am wondering how are people deploying and using this plugin?

Could you help?

**Comment by rozenmd** [comment]
@onoranzefunebricloud - Look into uploading the zip file to S3 first. You can point the Lambda function to the S3 file, and it will work.

**Comment by onoranzefunebricloud** [comment]
Hey @rozenmd, thanks for your answer.

I am using serverless framework which does that by default. Anyway, the limit is 250 MB of unzipped bundle - the bundle generated with this plugin is over 300 :(

Unless I am doing something completely stupid, would you mind sharing your set up? Are you using Serverless Framework? How do you bundle your lambdas?

Thanks!

**Comment by dcworldwide** [comment]
I'd love to see an example? Can't find a mention of this in the docs

**Comment by nicolas-yaros** [comment]
Any upates on this?
Just running "sls deploy" on the example package the size is 50.9mb, and the max size for lambda is 50mb

**Comment by blocka** [comment]
@onoranzefunebricloud did you ever find a solution?
