### ISSUE TITLE
Old binaries showing warning in screenshot

### ISSUE THREAD

**Issue by saamisam** [adieuadieu/serverless-chrome#252]
I am trying to take screenshot with puppeteer. It's working fine for all pages but when screenshot is taken on google search page it's showing warning.

url : https://www.google.com/search?q=wikipedia&oq=wikipedia&aqs=chrome.0.69i59j0l3j69i65j69i60l3.1508j0j4&sourceid=chrome&ie=UTF-8

screenshot-sample
![cropped](https://user-images.githubusercontent.com/31237558/73834155-35b6ef00-4831-11ea-987f-069dc485ff39.jpg)

Can you please provide latest binaries?

**Comment by adieuadieu** [comment]
New release now [available](https://github.com/adieuadieu/serverless-chrome/releases/tag/v1.0.0-57).
