### ISSUE TITLE
Builds failing on Mac with "index-pack died of signal 9"

### ISSUE THREAD

**Issue by sbressler** [adieuadieu/serverless-chrome#254]
I'm getting this error every time I build. Everything I've read about this issue on StackOverflow for other projects says that maybe RAM is an issue. The laptop has plenty of available memory. Is there some way to increase Docker memory? Some other issue happening here?

(new to Docker, but I'm an engineer and happy to dive in...)

Build output:
```bash
  ...
  xz-libs.x86_64 0:5.2.2-1.13.amzn1                                             

Complete!
Cloning into 'depot_tools'...
Cloning into 'src'...
error: index-pack died of signal 9
fatal: index-pack failed
The command '/bin/sh -c sh /build.sh' returned a non-zero code: 128
docker build -t "headless-chromium:$CHROMIUM_VERSION" --build-arg  "build"  0.14s user 0.16s system 0% cpu 9:58.54 total
```

**Comment by timo-a** [comment]
I have the same problem on Ubuntu. Did you manage to solve it?
