### ISSUE TITLE
unknown error: unable to discover pages

### ISSUE THREAD

**Issue by Denijar** [adieuadieu/serverless-chrome#255]
I keep encountering this error message when I try and run in AWS Lambda:
```
{
  "errorMessage": "Message: 'unknown error: unable to discover open pages\\n  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 4.14.165-102.205.amzn2.x86_64 x86_64)' ",
  "errorType": "WebDriverException",
  "stackTrace": [
    [
      "/var/task/src/lambda_function.py",
      35,
      "lambda_handler",
      "driver = webdriver.Chrome(chrome_options=chrome_options)"
    ],
    [
      "/var/task/lib/selenium/webdriver/chrome/webdriver.py",
      64,
      "__init__",
      "desired_capabilities=desired_capabilities)"
    ],
    [
      "/var/task/lib/selenium/webdriver/remote/webdriver.py",
      71,
      "__init__",
      "self.start_session(desired_capabilities, browser_profile)"
    ],
    [
      "/var/task/lib/selenium/webdriver/remote/webdriver.py",
      113,
      "start_session",
      "'desiredCapabilities': desired_capabilities,"
    ],
    [
      "/var/task/lib/selenium/webdriver/remote/webdriver.py",
      164,
      "execute",
      "self.error_handler.check_response(response)"
    ],
    [
      "/var/task/lib/selenium/webdriver/remote/errorhandler.py",
      164,
      "check_response",
      "raise exception_class(message, screen, stacktrace)"
    ]
  ]
}
```
This is the piece of code leading up to the point where the error occurs:
```
        chrome_options.add_argument('--disk-cache-dir=/tmp/cache-dir')
        chrome_options.add_argument('user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36')
        chrome_options.binary_location = os.getcwd() + "/bin/headless-chromium"

        driver = webdriver.Chrome(chrome_options=chrome_options)
```

I encounter this when I use the version stack that has been discussed [in this issue](https://github.com/adieuadieu/serverless-chrome/issues/133) as being a compatible set of versions (Python3.6, Selenium3.14, ChromeDriver2.43, Serverless Chrome v1.0.0-55).

Some Googling has suggested that adding `chrome_options.add_argument('--no-sandbox')` is a fix but this has not worked for me.

Any suggestions?

**Comment by jonmelia** [comment]
I'm having an identical issue, but with different versions:
selenium.common.exceptions.WebDriverException: Message: unknown error: unable to discover open pages
Driver info: chromedriver=2.41.578700 
Python:3.6
headlessChromium=69.0.3497.81

**Comment by jonmelia** [comment]
> I'm having an identical issue, but with different versions:
> selenium.common.exceptions.WebDriverException: Message: unknown error: unable to discover open pages
> Driver info: chromedriver=2.41.578700
> Python:3.6
> headlessChromium=69.0.3497.81

I managed to get this working by adding in the line below to the arguments I was passing.
options.add_argument('--single-process')

**Comment by Denijar** [comment]
@jonmelia could you post your full set of arguments? I already have --single-process and I am still getting the error.

**Comment by jonmelia** [comment]
These are all the arguments I'm using now...
    options.headless = True
    options.add_argument('start-maximized')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-extensions')
    options.add_argument('--single-process')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument('--disable-gpu')
    options.add_argument('--ignore-certificate-errors')
    options.add_argument('--hide-scrollbars')
