### ISSUE TITLE
Release Page Dead?

### ISSUE THREAD

**Issue by rooseveltrp** [adieuadieu/serverless-chrome#260]
Hi,

The release page looks pretty outdated. Is there are a prebuilt binary of Chrome 83.0.4103.97 for Amazon Linux?

Thanks

**Comment by 0xR** [comment]
I guess if you want a newer version you can build it yourself: https://github.com/adieuadieu/serverless-chrome/blob/master/docs/chrome.md

**Comment by falnyr** [comment]
Bump @adieuadieu. Maybe we could look into something like scheduled build with auto-release to github?

**Comment by sc250024** [comment]
Agreed. This could be automated, and this project still seems relevant. Curious what others are using though?

**Comment by 0xR** [comment]
This project seems more up to date https://github.com/alixaxel/chrome-aws-lambda

**Comment by sc250024** [comment]
@0xR Thanks for the tip. Unfortunately it requires me to use Node.js instead of Python. I need something more generic, like this project.

**Comment by adieuadieu** [comment]
New release now [available](https://github.com/adieuadieu/serverless-chrome/releases/tag/v1.0.0-57).
