### ISSUE TITLE
Build folder

### ISSUE THREAD

**Issue by zes** [adieuadieu/serverless-chrome#261]
Hello,

it is not an issue, sorry. But I don't know where to ask.
I build a Chromium locally, it was successful but I don't find where is the built Chromium ?
I'm surely missing something obvious but I don't find it.

Thank you.

**Comment by slewis-bd** [comment]
I haven't done a local build, but I did the EC2 build and it created a folder called `dist` and then copied the binary to that location before it zipped it up and uploaded to S3. The EC2 build cost less than $1USD using a c5a.8xlarge instance and took less than 60 minutes.
