### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by kaykhancheckpoint** [adieuadieu/serverless-chrome#269]
I get the following when error when trying to run this using serverless-webpack plugin.

>   Error: ENOENT: no such file or directory, link '/home/<redacted>/<redacted>/<redacted>/.build/handler.js' -> '/home/<redacted>/<redacted>/<redacted>/.build/hgu7v1gjjyg___handler.js'

I followed the documentation to make sure the order was correct but it still fails to work. 

```
plugins:
  - serverless-plugin-chrome
  - serverless-webpack
  - serverless-dotenv-plugin
```
I am using typescript so thats why i need serverless-webpack plugin.

Is there any solution to this problem?

**Comment by jjpark78** [comment]
me too, have same issue

**Comment by kaykhancheckpoint** [comment]
@jjpark78 i moved away from this library because of this issue i couldn't find a solution. 

I did find an alternative solution to use puppeteer in aws lambda if this is what you want.

To use puppeteer in aws lambda i created my own puppeteer lambda function  using the following https://github.com/alixaxel/chrome-aws-lambda

My other lambda functions would then call this new  puppeteer lambda function whenever i needed puppeteer.
