### ISSUE TITLE
Local build broken

### ISSUE THREAD

**Issue by timo-a** [adieuadieu/serverless-chrome#270]
I've cloned the latest version (85.0.4183.83) and attempt a local build as described here:
https://github.com/adieuadieu/serverless-chrome/blob/master/docs/chrome.md#locally
but `sudo docker build   -t "headless-chromium:$CHROMIUM_VERSION"   --build-arg VERSION="$CHROMIUM_VERSION"   "build"` is aborted with:
```
[0:30:37] Still working on:
[0:30:37]   src/third_party/angle/third_party/VK-GL-CTS/src
________ running 'vpython src/build/landmines.py' in '/build/chromium'
Hook 'vpython src/build/landmines.py' took 82.88 secs
________ running 'vpython src/third_party/depot_tools/update_depot_tools_toggle.py --disable' in '/build/chromium'
________ running 'vpython src/tools/remove_stale_pyc_files.py src/android_webview/tools src/build/android src/gpu/gles2_conform_support src/infra src/ppapi src/printing src/third_party/blink/renderer/build/scripts src/third_party/blink/tools src/third_party/catapult src/tools' in '/build/chromium'
________ running 'vpython src/buildtools/ensure_gn_version.py git_revision:7d7e8deea36d126397bda2cf924682504271f0e1' in '/build/chromium'
`/build/chromium/src/buildtools/linux64/gn --version` returned 1:
/build/chromium/src/buildtools/linux64/gn: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /build/chromium/src/buildtools/linux64/gn)

WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
use_relative_hooks is deprecated, please remove it from DEPS. (it was merged in use_relative_paths)
use_relative_hooks is deprecated, please remove it from DEPS. (it was merged in use_relative_paths)
Error: Command 'vpython src/buildtools/ensure_gn_version.py git_revision:7d7e8deea36d126397bda2cf924682504271f0e1' returned non-zero exit status 1 in /build/chromium
The command '/bin/sh -c sh /build.sh' returned a non-zero code: 2
```

It shouldn't matter since I'm building with docker but for what it's worth my OS is Ubuntu 18.04.

**Comment by teledyn** [comment]
I found a similar issue trying to build just the headless chrome from the build/build.sh script; there were several executables called gn available in other directories, just not in the path the build script expected.  I used `packages/lambda/builds/chromium/build/src/buildtools/linux64/gn` and it appeared to work. This was in AWS Linux 2.

**Comment by skunkworker** [comment]
Hi @timo-a this should be fixed now, over the last few months I noticed that every few months Chromium would update is GLIBC requirement and a newer version of the amazonlinux AMI would be required in order to build it, as older AMI releases did not have the newer GLIBC library.
