### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by yarikbratashchuk** [adieuadieu/serverless-chrome#30]
Hello)
@adieuadieu, could u, please, explain for me some simple stuff:

How is that possible that chrome can bind to the port 9222 on aws lambda?
Does it binds to a port at all?
I'm asking because i want to use binary with cdp client written in go.
Will it work at all?

Sincerely

**Comment by adieuadieu** [comment]
Hi @yarikbratashchuk. I'm not sure I understand your question. Chrome binds to port 9222 just like any other program can bind to a port. Lambda doesn't forbid you from creating ports. You should be able to use Go to connect to port 9222 from within a Lambda invocation. However, you won't be able to connect to the port from _outside_ of the Lambda function. Lambda functions do not have a public IP.

**Comment by yarikbratashchuk** [comment]
@adieuadieu thank u for the answer)
The go client makes get request to  http://127.0.0.1:9222/json/new, but gets "context deadline exceeded", that is why i asked, it doesn't work for me for now. 
How much memory this lambda probably need?

**Comment by adieuadieu** [comment]
Hi @yarikbratashchuk. I'm not familiar with that error message. Is there any more information in the function's CloudWatch logs? I would recommend running the function with _at least_ 1024 MB of memory. I usually use the maximum 1536 MB. Chrome is not.. lightweight.

**Comment by yarikbratashchuk** [comment]
@adieuadieu, this is what i get when try to test function via aws lambda dashboard:
``` "Get http://localhost:9222/json/new: dial tcp 127.0.0.1:9222: getsockopt: connection refused"```
```"context deadline exceeded"``` means that some time has passed but it didn't get a response from "http://127.0.0.1:9222/json/new".
Does headless_shell depends on some js stuff, to work?
Do i need to set ```--headless``` flag?
 
Thanks a lot

**Comment by adieuadieu** [comment]
Hm..

Launch the `headless_shell` with `--disable-gpu --single-process --no-zygote --no-sandbox` flags. If you want logging, add `--enable-logging --log-level=0 --v=99`. Try to capture or log the output from `headless_shell` to CloudWatch (in JS this is done with console.log.) There's usually some kind of error that gets logged by `headless_shell` if something went wrong.

**Comment by yarikbratashchuk** [comment]
@adieuadieu, seems like no logs on startup. I'm going to leave my go implementation and use your project.
