### ISSUE TITLE
Refactor into an npm package, serverless-plugin, and provide example handlers as individual Serverless functions

### ISSUE THREAD

**Issue by adieuadieu** [adieuadieu/serverless-chrome#4]
It seems to make a lot of sense to turn serverless-chrome into an npm package, and separate Serverless plugin.

The plugin would hook into the Serverless `after:createDeploymentArtifacts` life cycle event and wrap around the handler function. The wrapper would then make sure that headless Chrome is running before calling the wrapped handler function.

https://serverless.com/framework/docs/providers/aws/guide/plugins/

1. [x] update for nodejs v6.10 (and remove Buffer.from hack/polyfill)
1. [x] refactor chrome bundle and chrome spawning into an npm package (npm: `lambda-chrome` ?)
1. [x] Serverless plugin, using npm package
1. [x] use [Rollup](https://github.com/rollup/rollup)([docs](https://rollupjs.org/#introduction)) for npm packages
1. [x] remove `serverless-webpack` plugin dependency
1. [ ] create Serverless functions for each example handler
1. [x] ~change postinstall script to create `serverless.yml` instead of `config.js` from one of the example `serverless.yml` files~
1. [ ] update all the documentation

**Comment by bluepeter** [comment]
Can you reconsider using serverless, as that adds an opinionated framework? Perhaps just node-lambda or apex?

**Comment by bluepeter** [comment]
It would be nice to keep this without any framework dependency, particularly Serverless which is rather opinionated. Moreover, there's no current support in Serverless for versioning and aliases, which are integral to many AWS Lambda projects.

**Comment by adieuadieu** [comment]
Thanks for the feedback, @bluepeter! I agree with your request. I don't know whether I'd encourage _no_ framework because deploying to Lambda manually isn't particularly scalable/automate-able. However, I do intend to add support for at least a few more popular lambda-deployment tools. At least a couple from this list: Apex, Claudia.js, Gordon, Shep, DEEP, node-lambda, and/or Chalice.

The best way to make it possible to support multiple frameworks without too much code duplication, is to pull out the lambda-specific code for spawing a chrome process into it's own npm package that also bundles the headless chrome binary. This would open up the possibility for someone to easily roll their own custom solution using their own custom way of deploying to Lambda (which would satisfy your request.)

Furthermore, I also aim to make this project _provider_-less (e.g. support Azure and/or GCP) which is where having a framework like Serverless helps. As a consequence of these goals, this repository will end up being a mono-repo. I haven't documented this up anywhere, but here's my short-term roadmap for the project (over the next 2-4 weeks, notwithstanding changes as a result of feedback):

1. A Serverless-framework plugin which deals with bundling and spawning Chrome (via aforementioned lambda-headless-chrome npm package)
2. Add a few examples of how to do various things like capture a screenshot and save to S3, or how to manipulate DOM and/or do scraping or some testing
3. Add support for another framework (I think Apex—again, via the lambda-headless-chrome npm package)

**Comment by adieuadieu** [comment]
Actually, thinking about this some more.. the npm lambda-bundle would almost make the support for  frameworks like Serverless or Apex a bit redundant outside perhaps of some optimisations for each framework.. Perhaps that's what you were suggesting, @bluepeter...

E.g. given the npm package, one's lambda code could be agnostic to the framework..

```js
require('lambda-headless-chrome')(chromeFlagsOrConfigOptionsOrWhatever)
// or
const chrome = require('lambda-headless-chrome')

const someKindOfEventEmitter = chrome(chromeFlagsOrConfigOptions)
someKindOfEventEmitter.on('epic crash or something', () => { ... })



module.exports.handler = (event, context, done) {
    // do chrome-y stuff
    done()
}
```

**Comment by bluepeter** [comment]
I think this is definitely the right approach. Eager to see your progress on this!

**Comment by chriszarate** [comment]
Not sure what your progress has been on this, but I cobbled together a candidate npm module based on your implementation:

https://github.com/chriszarate/aws-lambda-headless-chrome

It bundles `chrome-remote-interface` and returns a promise that provides a CDP client:

```js
const lambdaChrome = require('lambda-chrome');
lambdaChrome({/* overriding options */).then(client => {
  const { Emulation, Page, Runtime } = client;
  /* do stuff */
});
```

A more complete example is in the repo (`example.js`). It doesn't implement an event emitter as you were discussing above, but I'm not exactly clear on the use case for that, especially if the CDP client is being provided.

Thoughts? I'd love to help push this forward but I don't want to create the module myself without your input—not least because I'm not set up to compile Chrome yet and am just warehousing your binaries. :)

**Comment by adieuadieu** [comment]
Hi @chriszarate,

Thanks for reaching out. Nice work on [aws-lambda-headless-chrome](https://github.com/chriszarate/aws-lambda-headless-chrome)!

I like your clean, simple implementation! I noticed that you decompress the tarball during the Lambda invocation. Be aware that this may add tens to hundres of milliseconds to the time consumed by the handler during it's cold-start invocaton. Perhaps consider bundling the decompressed version in the lambda function's package.zip.

As an aside: I saw a comment in your [readme](https://github.com/chriszarate/aws-lambda-headless-chrome/blob/master/README.md#notes) about the 50MB file-size limits imposed by Lambda on the package size. I was lead to believe the same thing by the limits described in the [AWS Lambda Limits documentation](http://docs.aws.amazon.com/lambda/latest/dg/limits.html), but it seems like it may be a "soft" limit. I've successfully deployed packages that are 95MB!

This project's progress on a standalone npm package is under the [v1.0](https://github.com/adieuadieu/serverless-chrome/tree/feature/v1.0/packages/lambda) branch

You can try it out with `npm` or `yarn`:

```bash
yarn add @serverless-chrome/lambda
```

Then use it in a Lambda function's handler:

```js
const launchChrome = require('@serverless-chrome/lambda')
const CDP = require('chrome-remote-interface')

module.exports.handler = function handler (event, context, callback) {
  launchChrome({
    flags: ['--window-size=1280x1696', '--hide-scrollbars']
  })
  .then((chrome) => {
    // Chrome is now running on localhost:9222

    CDP.Version()
      .then((versionInfo) => {
        callback(null, {
          versionInfo,
        })
      })
      .catch((error) => {
        callback(error)
      })
  })
  .catch((error) => {
    // Chrome didn't launch correctly

    callback(error)
  })
}
```

Just like you, I dropped the event emitter; it doesn't really make much sense. Furthermore, if you keep an event listener bound to the spawned Chrome process, the Lambda function won't end correctly as it'll just keep running waiting for events from Chrome until the execution timeout occurs.

I decided against bundling CDP straight into package. For example, you might want to connect two instances of CDP to two different tabs—so I leave connecting to Chrome up to the user. This gives the maximum flexibility for how a developer can use the module. The implementation in the v1.0 branch uses the [Lighthouse Chrome Launcher](https://github.com/GoogleChrome/lighthouse/tree/master/chrome-launcher) to spawn the `headless_shell` binary when run in the Lambda execution environment. The launcher tries to find another Chrome binary when run locally. This makes it convenient to develop locally with a local install of Chrome, or Chrome Canary. It also manages to start up Chrome much quicker than my original implementation. Shaves off between 500 to 1500ms!

So far I've only tested the `@serverless-chrome/lambda` module in a "vanilla" Lambda function and with the Serverless-framework. The Serverless-framework example is [here](https://github.com/adieuadieu/serverless-chrome/tree/feature/v1.0/functions/serverless-framework). Only the [version-info handler](https://github.com/adieuadieu/serverless-chrome/blob/feature/v1.0/functions/serverless-framework/src/versionInfo.js) is complete thus far, but demonstrates how you can use it.

With all that said, I'm definitely open to collaboration and PRs! For example I'd love to hear your feedback on using the `@serverless-chrome/lambda` package, ways to improve it, or to get together a ClaudiaJS usage example function in the [functions](https://github.com/adieuadieu/serverless-chrome/tree/feature/v1.0/functions)) collection.

**Comment by chriszarate** [comment]
Thanks for the response and feedback! Not sure how I missed your commit from earlier in the day.

RE: Lambda package size limits, I'll have to investigate that further. I definitely received a "too large" error response from Lambda when trying to package the decompressed binary. It's possible this error was specific to Claudia or something else in my environment. Perhaps this soft limit varies by AWS region?

The Lighthouse launcher logic and speed sounds great! Definitely makes sense to standardize on an "official" approach to launching.

I'll give your package a spin using Claudia and report back, possibly with a PR with an example for the collection.

One question: Is the plan to eventually publish to NPM unscoped, or will this remain a scoped package?

**Comment by adieuadieu** [comment]
@chriszarate About the "soft limit"—I've only tried in us-west-2 region but I doubt AWS would have variable "soft limits" in different regions. Not sure..

I'm undecided about the package scope. What are your thoughts?

**Comment by chriszarate** [comment]
@adieuadieu Hmm ... I got a chance to test the size limits again, with consistent results. It definitely points to the limits being variable—if not by region then perhaps by account.

I created a 64MB file resistant to compression:

```sh
dd if=/dev/urandom of=file.txt bs=1048576 count=64
```

Including this file in my payload, both for `us-east-1` and `us-west-2`, resulted in the following error response:

```
{ 
  message: 'Request must be smaller than 69905067 bytes for the CreateFunction operation',
  code: 'RequestEntityTooLargeException',
  time: 2017-06-02T21:42:17.259Z,
  requestId: '...',
  statusCode: 413,
  retryable: false,
  retryDelay: 74.10051249271442
}
```

I had a thought that perhaps only `CreateFunction` enforced the limit, but `UpdateFunctionCode` did not. However, creating a small function first, then adding the large file and updating, resulted in the same error.

(Curiously, the limit reported by the error message works out to 66.67 MB, which is also larger than the stated limit. Perhaps they are rolling out size increases on a fractional basis.)

As for the package scope, I think unscoped packages feel more "official," but that's purely anecdotal. Since it's discoverable via npmjs.com, I don't think it matters much.

**Comment by adieuadieu** [comment]
@chriszarate nice the size limit investigation! It's interesting that you're unable to upload over 50 MB. Here's a screenshot of some of my Lambda functions, over 50MB:

![screen shot 2017-06-09 at 3 46 29 pm](https://user-images.githubusercontent.com/438848/26978217-f9cd9ce0-4d2a-11e7-91fd-9bd453fbf1d3.png)

What's noteworthy is that these functions are deployed via the [Serverless-framework](https://github.com/serverless/serverless) tool, which uses CloudFormation to update the Lambda stack, and involves uploading the function's code package to S3. Perhaps the size limit is more lenient when done via S3? In the screenshot, the function with the 66.3MB code-size includes both the headless chrome and ffmpeg binaries.

**Comment by chriszarate** [comment]
@adieuadieu That's it! ClaudiaJS, by default, uploads the payload directly. However, it provides an option to upload via S3. Testing again, I was able to upload a larger payload:

```
claudia create --use-s3-bucket my-bucket --handler index.handler
```

Since your npm package includes the uncompressed binary, Claudia will in effect require the use of the `--use-s3-bucket` to successfully upload. That's a small price to pay for the resulting increase in spin-up speed, however.

I'll put together a PR with a Claudia example.

**Comment by adieuadieu** [comment]
@chriszarate nice! One thing I'm not clear on: Claudia doesn't produce a packaged zip file of the function code? I've left the headless chrome binary uncompressed in the npm package because my assumption was that it'll get compressed when the lambda function zip package is created—and there's really no compression benefit from double-zipping.

**Comment by chriszarate** [comment]
@adieuadieu Claudia does package a zip file (the test files I created were from `/dev/random` and therefore didn't compress much at all).

Leaving the binary uncompressed is not an issue; Claudia compresses that as expected. What I am seeing is that using Lighthouse as a dependency increases the payload size significantly. Using `@serverless-chrome/lambda` and about 2K of my code, bundling with Claudia produces zipped payload in the neighorhood of 85MB. This works when uploading via S3, but isn't ideal.

I notice that your use of `serverless` has a Webpack build step. I'm guessing that effectively does some tree-shaking to reduce to payload size. Claudia doesn't have a Webpack integration (I'm using Node 6.10–compatible ES2015 code) so I think it ends up bundling all of Lighthouse.

**Comment by adieuadieu** [comment]
@chriszarate thanks for the follow up. I've been working on the serverless-framework [plugin](https://github.com/adieuadieu/serverless-chrome/tree/feature/serverless-plugin/packages/serverless-plugin) and had similar concerns about the amount of dependencies Lighthouse introduces. Although the plugin will only include the minimum node modules that are required to run, it still adds about 500KB to the bundle. I end up having to make a [whitelist](https://github.com/adieuadieu/serverless-chrome/blob/feature/serverless-plugin/packages/serverless-plugin/src/index.js#L32) of stuff to include which I think is a bit brittle.

In Claudia, do you have any control over what gets included in the zip? In other words, are you able to include only the actual dependencies and not also devDependencies in the zip? When I cherry pick out only the actual dependencies, with `@serverless-chrome/lambda`, I end up with a zip that's  around 49MB. 47 or so of that is Chrome.

_Anyway_, I'm already thinking about removing the lighthouse dependency in `@serverless-chrome/lambda`. It brings along tons of it's own dependencies and just makes everything more complicated. _However_, it does make it easy to enable local development. So I'm torn.

**Comment by adieuadieu** [comment]
A quick follow-up: serverless@0.16.0 included [this feature](https://github.com/serverless/serverless/pull/3737) which _should_ make it easier to keep `devDependencies` out of the function artefacts when using Serverless.

**Comment by jgollub1** [comment]
Hi, thanks for all the work you've done! I was wondering if anyone could direct me to a web-scraping example (eg just rendering the DOM and returning it) of serverless-chrome that is deployable to aws lambda? I've been tinkering around with your package for a little while but haven't had much luck
