### ISSUE TITLE
ENOENT: no such file or directory, lstat '/Users/me/project-name/.build/.serverless'

### ISSUE THREAD

**Issue by Jud** [adieuadieu/serverless-chrome#45]
When running `serverless package` (and `serverless deploy`) I get an error when using `serverless-plugin-chrome`:

```
ENOENT: no such file or directory, lstat '/Users/me/project-name/.build/.serverless'
```

If I comment out the plugin from my `serverless.yml` `serverless package` works without issue (but no headless chrome).

I tried downgrading to older versions of serverless, but got the same error.

```
# serverless -v
1.17.0
```

**Comment by adieuadieu** [comment]
Hi @Jud Hm.. Which version of `serverless-plugin-chrome` are you using? Also, are you using any other plugins?

**Comment by Jud** [comment]
Hi @adieuadieu. I'm using `v1.0.0-9`. I also use `serverless-webpack`, from the serverless-es7 template: https://github.com/AnomalyInnovations/serverless-es7

Hope this helps!

**Comment by momer** [comment]
@Jud @adieuadieu When I switched from webpack to `serverless-plugin-typescript` this issue went away for me. Pretty much a drop-in replacement, but ideally this would work with both plugins

**Comment by adieuadieu** [comment]
@momer @Jud The plugin order is also important. `serverless-plugin-typescript` must come before `serverless-plugin-chrome`. However, `serverless-webpack` must come _after_ `serverless-plugin-chrome`. I've made sure that `serverless-plugin-chrome` works with `serverless-plugin-typescript` but have not yet had the chance to fully test with `serverless-webpack`—although it did work at once point. Still a bit of work to do to get all these parts to v1.0.

**Comment by Jud** [comment]
Hi @adieuadieu,

I'm including `serverless-webpack` after `serverless-plugin-chrome`. `serverless-webpack` does some caching and build path manipulation (which I noticed `serverless-plugin-chrome` does as well). It wouldn't surprise me if that's the root of the issue.

**Comment by adieuadieu** [comment]
@Jud I'll publish a fix for the `serverless-webpack` plugin soon.

**Comment by carlosbaraza** [comment]
Hello @adieuadieu, do you have any updates on this issue?

Thanks for the great work!
