### ISSUE TITLE
unable to install using yarn

### ISSUE THREAD

**Issue by billdesk** [adieuadieu/serverless-chrome#50]
git clone https://github.com/adieuadieu/serverless-chrome
cd serverless-chrome
yarn install

ERROR: [Errno 2] No such file or directory: 'install'

root@nodejs:~/serverless-chrome# ls
CHANGELOG.md  chrome  circle.yml  LICENSE  node_modules  package.json  README.md  serverless.yml  src  webpack.config.js  yarn.lock

I tried npm install followed by yarn deploy
root@nodejs:~/serverless-chrome# yarn deploy
ERROR: [Errno 2] No such file or directory: 'deploy'

am i missing anything.

**Comment by adieuadieu** [comment]
@billdesk do you have `yarn` installed? Try `yarn --version`. Make sure you have at least v0.27.5. Alternatively you can always replace `yarn` with `npm`. If it's `yarn xxx` then with `npm` you'd do `npm run xxx` . E.g. `yarn deploy` would be `npm run deploy`.

**Comment by billdesk** [comment]
Thanks @adieuadieu 

I tried npm run install and i got the following error.
root@nodejs:~/serverless-chrome# npm run install
npm ERR! Linux 4.4.0-87-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! missing script: install
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/serverless-chrome/npm-debug.log


I have yarn version  0.22

**Comment by adieuadieu** [comment]
@billdesk In the case of install, on npm, it's `npm install`. While it should work, you may still want to update `yarn` to the latest version.
