### ISSUE TITLE
NSS_VersionCheck("3.26") failed

### ISSUE THREAD

**Issue by masonator** [adieuadieu/serverless-chrome#53]
Hello,

I get the below at runtime when I follow the build steps and then try to run on Lambda. Has anyone come across this? Chrome was compiled on the same AMI as Lambda uses and followed the instruction in this repo.

```
[0807/144244.712736:FATAL:nss_util.cc(627)] NSS_VersionCheck("3.26") failed. NSS >= 3.26 is required
Please upgrade to the latest NSS, and if you still get this error,
contact your distribution maintainer.
```

**Comment by adieuadieu** [comment]
Hi @masonator I'm currently also stuck on this. 😟

**Comment by masonator** [comment]
Hi @adieuadieu, spent some time on this.

The issue that Chrome 62 now requires a higher version of nss than comes on the Lambda AMI by default. Solution is to build an older version of Chrome, which you can do like this:

```
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
echo "export PATH=$PATH:$HOME/depot_tools" >> ~/.bash_profile
source ~/.bash_profile
mkdir Chromium && cd Chromium
fetch chromium
cd src
git checkout 60.0.3112.96
gclient sync --with_branch_heads --jobs 16
```

**Comment by adieuadieu** [comment]
@masonator Yes; that's correct. Unfortunately, having to build an older version is a no-go for serverless-chrome, so the question becomes: can we disable the NSS version check, and if we do, what does it break, _or_ can we get AWS to upgrade the version used in Lambda (hahahah unlikely) **or**, can we somehow include our own version and point Chrome to it.

**Comment by qubyte** [comment]
I've found a solution to this. I'll put together a PR with details.

**Comment by akbarbin** [comment]
I have done to fix this in Ubuntu 16.04 by reinstalling `libnss3`.
Code

`sudo apt-get install --reinstall libnss3`

I found the here [https://ubuntuforums.org/showthread.php?t=2178663#post_message_12807565](url)

**Comment by krworks** [comment]
The only solution that worked for me was to download xenial's libnss3 manually from
https://packages.ubuntu.com/xenial/amd64/libnss3/download

Then install:
`sudo dpkg -i libnss3_3.28.4-0ubuntu0.16.04.3_amd64.deb`

**Comment by lweo** [comment]
@akbarbin   Thx!  really helpful!

**Comment by Bogdan-Math** [comment]
@akbarbin thanks, it realy works for Linux Mint 18 Sarah.

**Comment by acowpy** [comment]
Hi

I had the same issue in Ubuntu 16.04. apt won't update to the latest version of libnss3 by default so you have to enable security updates.

1) Open 'Software Updater', then click on 'settings' button
2) Tick the 'important Security Updates (xenial-security) then close. it will update the cache
3) Open terminal and then run the command 'sudo apt-get install libnss3'

Should then work

**Comment by adieuadieu** [comment]
Quick note: this issue is resolved in the latest prereleases

**Comment by mssiddiqui** [comment]
Even with 14.04 Ubuntu below steps were fine in my case -
sudo apt-get update
sudo apt-get install libnss3

**Comment by VishakhaOhal31** [comment]
After installing linbnss3, Chrome browser is opening . Thanks for the solution

**Comment by nabilaholic211** [comment]
After installing linbnss3, thannks . its work

**Comment by meajinkya** [comment]
@akbarbin Thanks a lot! worked on Ubuntu 14.04.

**Comment by inyee786** [comment]
@krworks thanks finally the application is working

**Comment by fusion27** [comment]
# @krworks, thank you! 👍️

1. Found the xenial `libnss3` package here, fetched & installed
> https://packages.ubuntu.com/xenial/amd64/libnss3/download
```sh
wget http://security.ubuntu.com/ubuntu/pool/main/n/nss/libnss3_3.28.4-0ubuntu0.16.04.9_amd64.deb
sudo dpkg -i libnspr4_4.13.1-0ubuntu0.16.04.1_amd64.deb
```

2. Found the xenial `libnspr4` package here, fetched & installed
> https://packages.ubuntu.com/xenial/amd64/libnspr4/download
```sh
wget http://security.ubuntu.com/ubuntu/pool/main/n/nspr/libnspr4_4.13.1-0ubuntu0.16.04.1_amd64.deb
sudo dpkg -i libnss3_3.28.4-0ubuntu0.16.04.9_amd64.deb
```
