### ISSUE TITLE
Should we modify post-install?

### ISSUE THREAD

**Issue by quangbuule** [adieuadieu/serverless-chrome#55]
In @serverless-chrome/lambda, we are downloading chrome binaries every npm (and yarn) add/remove commands.
Should we add some check for not downloading same files all over again?

**Comment by adieuadieu** [comment]
Hi @quangbuule yes you're absolutely right. The postinstall.js script should check if for an already existing tarball that was previously downloaded. I'd be happy to accept a PR for this. 😃

**Comment by frosty5689** [comment]
Hi, just adding to this. It would be nice if you can change this to delete the zip after unzip and check the existence and checksum of the Chrome binary before downloading the zip again. This would solve the headache of serverless-webpack packaging both the zip and the binary into the package. I haven't been able to find a way to exclude the zip when using serverless-webpack.
