### ISSUE TITLE
Chrome 61

### ISSUE THREAD

**Issue by lawlmart** [adieuadieu/serverless-chrome#57]
https://github.com/adieuadieu/serverless-chrome/tree/develop says the current version of Crome is 61, but the one I'm getting is 60. Any idea how to upgrade versions?

Thanks

**Comment by adieuadieu** [comment]
Hi @lawlmart This is a mistake. We tried to upgrade to 61, but this introduced an issue in Lambda which we've been blocked by for a bit (recently resolved by #56).
