### ISSUE TITLE
Can't install using yarn or npm

### ISSUE THREAD

**Issue by boosh** [adieuadieu/serverless-chrome#58]
I can't get this to install using either method on the README:

Install with yarn (v0.27.5) `yarn add @serverless-chrome/lambda` gives the error:
```
yarn add v0.27.5
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@serverless-chrome%2flambda: User not found".
```
Install with npm (v5.3.0) `npm install --save @serverless-chrome/lambda` gives the error:
```
npm ERR! code E404
npm ERR! 404 Not Found: @serverless-chrome/lambda@latest
```

**Comment by tnolet** [comment]
@boosh are you using a proxy or some 3rd party local NPM registry like SInopia? I was, and I fixed this issue by setting the registry to the default one:
```
npm config set registry https://registry.npmjs.org/
```

**Comment by adieuadieu** [comment]
Thank you for the tip @tnolet!

**Comment by boosh** [comment]
@tnolet Yes, I was. I renamed my `~/.npmrc` file and now I can install it. Thanks!
