### ISSUE TITLE
Google Fonts is not loaded

### ISSUE THREAD

**Issue by chemitaxis** [adieuadieu/serverless-chrome#64]
Hi, I have tested the chromeless with a page, and the fonts is not loading... 

The screenshot is fine, but the fonts loaded for example with [webfont loader](https://github.com/typekit/webfontloader), is not working...  

This is the example: 

```
const chromeless = new Chromeless({ remote: true, viewport: {width: 800, height: 1600} })

const screenshot = await chromeless
  .goto('https://www.genial.ly/View/Index/5901d777ba1ab76840eafbcc')
  .wait(5000)
  .screenshot()

console.log(screenshot)

await chromeless.end()

```
And [this is the link](https://www.genial.ly/View/Index/5901d777ba1ab76840eafbcc), and you can check that the font is loaded in Chrome.

Any ideas? Thanks.

**Comment by henrikhaugboelle** [comment]
Did anyone manage to solve this issue? :-)
