### ISSUE TITLE
README suggests you can deploy from Windows

### ISSUE THREAD

**Issue by SidneyNemzer** [adieuadieu/serverless-chrome#67]
As you know, [you can't deploy this project from Windows][windows-deploy-issue], because Windows' file permissions system doesn't line up Unix's.

However, the README suggests otherwise:

> This package bundles a lambda-execution-environment-ready headless Chrome binary which allows you to deploy from any OS

https://github.com/adieuadieu/serverless-chrome/blob/master/README.md#setup-and-deployment

[windows-deploy-issue]: https://github.com/adieuadieu/serverless-chrome/issues/21

**Comment by SidneyNemzer** [comment]
For anyone who cares, my workaround for the Windows-deploy-problem is just to use a Cloud 9 workspace to deploy from.

**Comment by adieuadieu** [comment]
Closing this Issue as it's been addressed.

**Comment by uzhas-sovka** [comment]
Hi Sidney, how did you manage to deploy from Cloud9? I have this issue
https://github.com/adieuadieu/serverless-chrome/issues/151
Thanks...

**Comment by SidneyNemzer** [comment]
Hey @uzhas-sovka, sorry to hear that you're having problems. We're deploying to a Lamda function, rather than EC2, although I'm not sure that makes a difference. I don't recall having any errors when deploying from C9.

Something to note, we're still using an old version of this package. In fact, at the time, it was *not* a package, the install instructions were simply cloning the repo and adding in your function code. We have not had time to update to the new version. I'm not sure how much the deploy process has changed.
