### ISSUE TITLE
How to run this project localy?

### ISSUE THREAD

**Issue by gitowiec** [adieuadieu/serverless-chrome#70]
I would like to run this project on my Debian to develop more features, how to begin with setup?
Could someone provide simple (not necessarily detailed) steps to "deploy" serverless-chrome to my linux laptop?
Best regards

**Comment by adieuadieu** [comment]
Hi @gitowiec — If you mean _using_ the project, have you seen [this](https://github.com/adieuadieu/serverless-chrome/tree/develop/packages/serverless-plugin#local-development)?

**Comment by gitowiec** [comment]
@adieuadieu thank you for your reply. I managed to run it with serverless-offline. Everything went SNAFU, because I didn't know a scrub about AWS, Lambda and Serverless - BUT I managed to deploy my own version of your project. Mine sends back base64 encoded PDFs printed from received HTML files zipped with resource files (js and css).
