### ISSUE TITLE
Flash support

### ISSUE THREAD

**Issue by eirslett** [adieuadieu/serverless-chrome#75]
Am I crazy, you might ask, it's 2017. Flash is dead and all of that. Well, you know, legacy project, it has a little flash component in it, cannot easily be ported to webassembly etc. All I want is to write selenium tests...

So I tried downloading Flash (libpipflashplayer.so) from https://get.adobe.com/flashplayer/otherversions/ and running chrome in a lambda with a couple of extra command line flags:

```
--disable-component-update
--always-authorize-plugins
--allow-outdated-plugins
--ppapi-flash-path=/var/task/lib/libpepflashplayer.so
```

Unfortunately, Flash still doesn't work on my page... has anybody else hit this problem and found a solution for it?

**Comment by adieuadieu** [comment]
Hi @eirslett — Hm.. There are many things working against you.

Have you tried getting this to work locally or in [Docker](https://hub.docker.com/r/yukinying/chrome-headless/)? I suggest also asking on the [headless-dev](https://groups.google.com/a/chromium.org/forum/#!forum/headless-dev) group to ask if this is even theoretically possible with headless chromium. Headless Chromium deals with plugins and extensions a bit differently than "regular" Chromium  (or, doesn't support them at all) which might make running Flash impossible. If it _is_ possible, then you'll have to make sure that the Lambda execution environment has all the dependencies required to run `libpepflashplayer.so` successfully. If it's missing dependencies, you'll have to figure out what they are and package them with your Lambda function.

Also, double-check those flags. This serverless-chrome ships with the Chromium [headless_shell](https://chromium.googlesource.com/chromium/src.git/+/master/headless) which is a bit different from the version of Chrome you'd install locally. As a consequence, the flags which you might use for "regular" Chrome are not always available/used in the headless_shell version ([here](https://chromium.googlesource.com/chromium/src.git/+/master/headless/app/headless_shell_switches.h) and [here](https://chromium.googlesource.com/chromium/src.git/+/master/content/public/common/content_switches.h) for available switches/flags.)

**Comment by joelgriffith** [comment]
Apparently might be on the Chrome side: https://bugs.chromium.org/p/chromedriver/issues/detail?id=187

**Comment by adieuadieu** [comment]
@joelgriffith started a thread (thank you!) asking the question of Flash support on the headless-dev group [here](https://groups.google.com/a/chromium.org/forum/#!msg/headless-dev/mC0REfsA7vo/rKAZdRrCCQAJ)

The response from Eric Seckler is not promising for those who need Flash support:

> Plugins, like Chrome extensions, are not currently supported in headless AFAIK and there's no work being done to add Flash support right now. I'm not sure whether it's feasible to make Flash or plugins in general work with headless, particularly since Flash is on the deprecation path, see https://blog.chromium.org/2017/07/so-long-and-thanks-for-all-flash.html.
