### ISSUE TITLE
PrintToPdf Handler

### ISSUE THREAD

**Issue by mario589736** [adieuadieu/serverless-chrome#78]
I am creating a pdf like it is in the PrintToPdf Handler. After That i upload it to s3. My Problem is that i am always uploading pdfs which are not completed. (e.g. images are missing)

so i put a timeout behind:

    const pdf = await Page.printToPDF(printOptions)
    await sleep(18000)

any idea why the timeout is not working at this position? how do you normally manage this problem?

**Comment by adieuadieu** [comment]
Hi @mario589736 — The sleep needs to come before `Page.printToPDF()`. It's too late afterwards as the PDF has already been generated.

However, simply sleeping isn't the best solution. It's much better to wait for a request queue to empty and then generate the PDF. This is implemented in the `develop` branch [here](https://github.com/adieuadieu/serverless-chrome/blob/develop/examples/serverless-framework/aws/src/chrome/pdf.js#L47). Unfortunately, I'm in the middle of refactoring that code so your mileage may vary if you copy it.

**Comment by mario589736** [comment]
Thanks @adieuadieu, before the timeout i had the 
    Page.loadEventFired()
promise. Which seemed to fire before the pdf was created. now i have this setup: 
    await Page.navigate({url})
    await sleep(18000)
    const pdf = await Page.printToPDF(printOptions)
    await sleep(5000)

Which is working, but no bulletproof. Thanks for the link to the queue solution, i will try that one.

**Comment by mario589736** [comment]
solved with the queue solution :) - thanks

**Comment by adieuadieu** [comment]
Great! 😄
