### ISSUE TITLE
Error printing pdf for URL - ECONNRESET

### ISSUE THREAD

**Issue by mario589736** [adieuadieu/serverless-chrome#79]
It seems that Chrome does not answer every 5 - 6 lambda calls. @adieuadieu - do you think there is a link to the [ #41](https://github.com/adieuadieu/serverless-chrome/issues/41) error? If yes switching to the dev branch is the best option right? Or any other ideas?

Full Error Stack:
   ```
 2017-10-19T13:14:09.057Z	64116166-b4cf-11e7-bc89-2b60ceaa6ca0	Error printing 
    pdf for google.com
{ Error: read ECONNRESET at exports._errnoException (util.js:1018:11) at TCP.onread (net.js:568:26) code:  'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }2017/10/19/[$LATEST]d17e15b02ea544c4b66ea662c8c379df2017-10-19T13:14:09.057Z64116166-b4cf-11e7-bc89-2b60ceaa6ca0	Error printing pdf for https://staging.buzzbird.de/brand/directaccess/reporting/3683 { Error: read ECONNRESET at exports._errnoException (util.js:1018:11) at TCP.onread (net.js:568:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
```

**Comment by adieuadieu** [comment]
@mario589736 Sounds like that's the same issue as #41. I will publish a new binary and npm package (on the develop branch) over the next few days which will include the comment-out hack described [here](https://github.com/adieuadieu/serverless-chrome/issues/41#issuecomment-341712878).

I'll close this Issue in favor of #41.
