### ISSUE TITLE
Reduce binary size with upx 

### ISSUE THREAD

**Issue by vladgolubev** [adieuadieu/serverless-chrome#80]
Hey, did you try compressing the binary with https://github.com/upx/upx ? It may shrink size twice or more

**Comment by adieuadieu** [comment]
Hi @vladgolubev. [Yes I did](https://github.com/adieuadieu/serverless-chrome/blob/f01fd2c502e6de928953269d290a26eb59aa0461/packages/lambda/builds/chromium/build/Dockerfile#L44-L55). Unfortunately it increases the startup time by 1000-1500 ms on AWS Lambda which I felt was not a good trade-off. However, [new stable builds](https://github.com/adieuadieu/serverless-chrome/releases/tag/v1.0.0-6) are [`strip`ed](https://github.com/adieuadieu/serverless-chrome/blob/f01fd2c502e6de928953269d290a26eb59aa0461/packages/lambda/builds/chromium/build/Dockerfile#L42) which helps reduce the binary size by around 45MB.

**Comment by vladgolubev** [comment]
Thanks for the info ! Good to know !
