### ISSUE TITLE
Lambda server error

### ISSUE THREAD

**Issue by 416serg** [adieuadieu/serverless-chrome#81]
I've deployed a slightly modified version to Lambda and everything seems to work fine, however, when I run a few executions one after another, some return a server error from the function.

Is this a Lambda issue or serverless-chrome? I guess I don't know enough about the actual process that happens on Lambda to know if Chrome is failing on that end 😢

**Comment by adieuadieu** [comment]
Hi @416serg — That sounds like #41. Good news is that a fix has been proposed and a new Chromium binary forthcoming.
