### ISSUE TITLE
Error: 'Network.setCookies' wasn't found

### ISSUE THREAD

**Issue by ile** [adieuadieu/serverless-chrome#86]
I'm trying to set cookies and I have some code like this:

```js
Promise.all([
  client.send('Network.enable', {}),
  client.send('Network.setCookies', { cookies: [{ acookie: true }]})
]).then(function() {
  return client.send('Page.navigate', { url });
}).catch(function(err) {
  console.error(err);
});
```
I get this error though: `Error: 'Network.setCookies' wasn't found`

When I try this (or some example code they have) with Puppeteer, it seems to work.

Am I doing maybe something wrong or is the `headless_shell` binary perhaps not supporting this?

**Comment by adieuadieu** [comment]
Hi @ile Hm.. It might be that `Network.setCookies` does not yet exist in the Chrome Debugging Protocol version that ships with the latest Stable-channel version of Chromium. It's difficult to tell when `Network.setCookies` was introduced looking at [the documentation](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setCookies). You could try [specifying another](https://github.com/adieuadieu/serverless-chrome/tree/master/packages/lambda#specifying-chromium-channel) binary (dev or beta channels) for serverless-chrome to use. Alternatively you could loop over `Network.setCookie` (singular). Something along the lines of:

```typescript
for (const cookie of cookies) {
    await Network.setCookie({
      ...cookie,
      url: getUrlFromCookie(cookie),
    })
}
```
[source](https://github.com/graphcool/chromeless/blob/master/src/util.ts#L357-L362)

**Comment by ile** [comment]
Hi @adieuadieu and thanks for the tip & reply. `Network.setCookie` seems to work. 

Closing this for now.
