### ISSUE TITLE
🎉 Remove the Chromium /dev/shm hack on new 64+ builds as it's no longer needed since 64.0.3281.0

### ISSUE THREAD

**Issue by adieuadieu** [adieuadieu/serverless-chrome#87]
Remove the Chromium /dev/shm hack on new 64+ builds as it's no longer needed since 64.0.3281.0  🎉 

https://bugs.chromium.org/p/chromium/issues/detail?id=736452#c37

**Comment by adieuadieu** [comment]
Released in [v1.0.0-45](https://github.com/adieuadieu/serverless-chrome/releases/tag/v1.0.0-45)

**Comment by skunkworker** [comment]
Can we put that adding the `--disable-dev-shm-usage` flag to chrome will get rid of chrome complaining about not enough memory in /dev/shm somewhere?
