### ISSUE TITLE
Remove `mobile` parameter

### ISSUE THREAD

**Issue by 416serg** [adieuadieu/serverless-chrome#88]
I am working on an extension of the `screenshot` example, but I don't need to know wether the device screenshot needs to be mobile or desktop, so I did a bit of refactoring.

In `src/chrome/ruutshot.js`

```
export default async function captureScreenshotOfUrl (url, ruutId, userId, env, company) {
   /* All the stuffs here */
}
```

in `src/handlers/ruutshot.js`

```
const { queryStringParameters: { url, ruutId, userId, env, company } } = event
// All the other stuffs
```

However I am still getting the following error in cloudwatch

```
2017-12-01T20:03:41.826Z	b927357d-d6d2-11e7-a0f2-1f9587ac1fdd	{ Error: Invalid parameters (mobile: boolean value expected)
at ProtocolError (/var/task/src/handlers/ruutshot.js:17461:9)
at /var/task/src/handlers/ruutshot.js:17533:30
at Chrome.handleMessage (/var/task/src/handlers/ruutshot.js:17734:13)
at WebSocket.<anonymous> (/var/task/src/handlers/ruutshot.js:17711:27)
at emitOne (events.js:96:13)
at WebSocket.emit (events.js:188:7)
at Receiver._receiver.onmessage (/var/task/src/handlers/ruutshot.js:13443:47)
at Receiver.dataMessage (/var/task/src/handlers/ruutshot.js:14758:14)
at perMessageDeflate.decompress (/var/task/src/handlers/ruutshot.js:14718:40)
at _decompress (/var/task/src/handlers/ruutshot.js:456:9)
response: 
{ code: -32602,
message: 'Invalid parameters',
data: 'mobile: boolean value expected' } }
```

I cannot find any references to me defining the mobile query to be required 😕

**Comment by adieuadieu** [comment]
Hi @416serg — The `Invalid parameters` error message is coming from the Chrome Debugging Protocol. This means that, you're likely still passing some value ([here](https://github.com/adieuadieu/serverless-chrome/blob/master/examples/serverless-framework/aws/src/chrome/screenshot.js#L44) or [here](https://github.com/adieuadieu/serverless-chrome/blob/master/examples/serverless-framework/aws/src/chrome/screenshot.js#L65)) for `mobile` to the `Emulation.setDeviceMetricsOverride` method.

**Comment by 416serg** [comment]
@adieuadieu thanks for jumping on this! 😄 

I removed the second `Emulation` and changed the first one to 

```
await Emulation.setDeviceMetricsOverride({
      deviceScaleFactor: 0,
      scale: 1, // mobile ? 2 : 1,
      fitWindow: true,
      width: 1200,
      height: 625,
    })
```

Yet I am still seeing the error in CloudWatch logs.

**Comment by adieuadieu** [comment]
Ah. That's my mistake—didn't read the documentation closely enough. It [looks like](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDeviceMetricsOverride) the `mobile` parameter is _required_. I guess in your case, just set it to `false`.
