### ISSUE TITLE
Can't install example app on Mac OS

### ISSUE THREAD

**Issue by anzebra** [adieuadieu/serverless-chrome#90]
Hello, I am stuck in the very beginning :) I'm trying to run the next command:

```
serverless create -u https://github.com/adieuadieu/serverless-chrome/tree/master/serverless-chrome/examples/serverless-framework/aws
```

But output is always the same:

```
Serverless: Generating boilerplate...
Serverless: Downloading and installing "aws"...

  Serverless Error ---------------------------------------

  Error: EEXIST: file already exists, symlink '../dist/' -> '/var/folders/xz/fmlcpsh92zn23tv701vvynfh0000gn/T/serverless-chrome/packages/lambda/integration-test/dist'

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.9.1
     Serverless Version:     1.24.1
```
I tried 3 different macs, and the problem is the same on all of them.

**Comment by adieuadieu** [comment]
That's no good. Sorry about that. 😞 

Alternatively, you can try:

```sh
git clone https://github.com/adieuadieu/serverless-chrome.git
cd serverless-chrome/examples/serverless-framework/aws
[ -n "$(which yarn)" ] && yarn install || npm install
```

Now you should be as far as you'd be doing `serverless create -u ...`

**Comment by anzebra** [comment]
Great, thanks @adieuadieu, that really helped!

**Comment by adieuadieu** [comment]
@anzebra glad to hear that helped!

I'm going to re-open this Issue thread as the original reported problem has not been corrected, and I'd like to make sure it gets fixed.

**Comment by miherlosev** [comment]
Hi, @adieuadieu
I have a same error in Ubuntu 16.04 LTS.
To fix the problem I use provided you solution:
```js
git clone https://github.com/adieuadieu/serverless-chrome.git
cd serverless-chrome/examples/serverless-framework/aws
[ -n "$(which yarn)" ] && yarn install || npm install
```
But I don't understand which command I should perform after this.
Could you please provide a more detailed instructions?

**Comment by jgollub1** [comment]
I'm still getting the same error as originally reported when running 'serverless create.' Was this ever fixed? Thanks!
